### ISSUE TITLE
quarkus-langchain4j-workshop/step-04 does not work with Ollama

### ISSUE THREAD

**Issue by jordensy** [quarkiverse/quarkus-langchain4j#1001]
I am doing the https://github.com/cescoffier/quarkus-langchain4j-workshop
But I got stuck on step 04

Since I do not have an OPENAI KEY I am using this with Ollama.

I have:

io.quarkus.platform 3.15.1
io.quarkiverse.langchain4j 0.20.3
Java version = 21.0.1" 2023-10-17 LTS
mvn plugin 3.13.0 
quarkus-mvn 3.15.1
Running from InteliJ ultimate 2024.1

When I use `@SessionScoped` I get an error this interface is not Serializable and that it needs to be a concrete class

```java
@SessionScoped
@RegisterAiService
public interface CustomerSupportService extends Serializable {

          Multi<String> chat(@UserMessage String userMessage);
}
```

I couldn't fine a proper solution so I disabled the CDI inspection for this error But then I get below error:

```posh
2024-10-21 10:13:27,446 WARN  [io.qua.lan.dep.JandexUtil] (build-19) 'java.io.Serializable' used for creating an AiService is not an interface. Attempting to create an AiService using this class will fail
2024-10-21 10:13:27,491 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2024-10-21 10:13:27,943 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.langchain4j.deployment.AiServicesProcessor#handleAiServices threw an exception: java.lang.NullPointerException: Cannot invoke "org.jboss.jandex.ClassInfo.name()" because "directSubInterface" is null
        at io.quarkiverse.langchain4j.deployment.JandexUtil.getAllSuperinterfaces(JandexUtil.java:54)
        at io.quarkiverse.langchain4j.deployment.AiServicesProcessor.handleAiServices(AiServicesProcessor.java:876)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
        at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:499)

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:354)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:272)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:62)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:89)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:428)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:55)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.langchain4j.deployment.AiServicesProcessor#handleAiServices threw an exception: java.lang.NullPointerException: Cannot invoke "org.jboss.jandex.ClassInfo.name()" because "directSubInterface" is null
        at io.quarkiverse.langchain4j.deployment.JandexUtil.getAllSuperinterfaces(JandexUtil.java:54)
        at io.quarkiverse.langchain4j.deployment.AiServicesProcessor.handleAiServices(AiServicesProcessor.java:876)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
        at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:499)

        at io.quarkus.builder.Execution.run(Execution.java:124)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:161)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:350)
        ... 9 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.jboss.jandex.ClassInfo.name()" because "directSubInterface" is null
        at io.quarkiverse.langchain4j.deployment.JandexUtil.getAllSuperinterfaces(JandexUtil.java:54)
        at io.quarkiverse.langchain4j.deployment.AiServicesProcessor.handleAiServices(AiServicesProcessor.java:876)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
        at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:499)
```

**Comment by geoand** [comment]
Thanks for repotring.
I'll have a look soon

**Comment by geoand** [comment]
I just tried it and I can't reproduce the problem.

**Comment by jordensy** [comment]
So, any idea where I need to look at?
It must be 
some local problem then but I have no idea where to look.

I am running on Windows 11 Enterprise

This is the code (all *.TXT to be able to upload):

[pom.txt](https://github.com/user-attachments/files/17465385/pom.txt)
[application.txt](https://github.com/user-attachments/files/17465399/application.txt)
[CustomerSupportAgentWebSocket.txt](https://github.com/user-attachments/files/17472779/CustomerSupportAgentWebSocket.txt)
[CustomerSupportService.txt](https://github.com/user-attachments/files/17472780/CustomerSupportService.txt)

**Comment by jordensy** [comment]
[step-01.zip](https://github.com/user-attachments/files/17473320/step-01.zip)

**Comment by geoand** [comment]
Try using Quarkus LangChain4j version `0.20.3`

**Comment by jordensy** [comment]
as you can see in the POM, I already tried that (it is in comment). I was trying previous versions to see if this would do any help. But Initially I was testing with 0.20.3. But I have the same issue then.

**Comment by jordensy** [comment]
Yes that  is the title of this issue. That is how started and ran into this issue.

**Comment by geoand** [comment]
Using the following `pom.xml` works fine for me:

```xml
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>

    <groupId>dev.langchain4j</groupId>
    <artifactId>quarkus-langchain4j-workshop-01</artifactId>
    <version>1.0.0</version>

    <properties>
        <maven.compiler.release>21</maven.compiler.release>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <compiler-plugin.version>3.13.0</compiler-plugin.version>

        <quarkus.platform.version>3.16.0.CR1</quarkus.platform.version>
        <quarkus-langchain4j.version>0.20.3</quarkus-langchain4j.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.quarkus.platform</groupId>
                <artifactId>quarkus-bom</artifactId>
                <version>${quarkus.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>

        <dependency>
            <groupId>io.quarkiverse.langchain4j</groupId>
            <artifactId>quarkus-langchain4j-ollama</artifactId>
            <version>${quarkus-langchain4j.version}</version>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest</artifactId>
        </dependency>

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-websockets-next</artifactId>
        </dependency>

        <!-- UI -->
        <dependency>
            <groupId>org.mvnpm</groupId>
            <artifactId>importmap</artifactId>
            <version>1.0.8</version>
        </dependency>
        <dependency>
            <groupId>org.mvnpm.at.mvnpm</groupId>
            <artifactId>vaadin-webcomponents</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.mvnpm</groupId>
            <artifactId>es-module-shims</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.mvnpm</groupId>
            <artifactId>wc-chatbot</artifactId>
            <version>0.2.0</version>
            <scope>runtime</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${compiler-plugin.version}</version>
                <configuration>
                    <compilerArgs>
                        <arg>-parameters</arg>
                    </compilerArgs>
                </configuration>
            </plugin>

            <plugin>
                <groupId>io.quarkus.platform</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.platform.version}</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate-code</goal>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>
</project>

```

**Comment by jordensy** [comment]
Know it works with your POM but there is no difference with mine original.
I did a mvn:clean (maybe somthing got stuck)


Anyway you may close this issue. Many thanks for your quick and helpfull support.

**Comment by geoand** [comment]
👍🏽
