### ISSUE TITLE
Dev UI chat page broken if there are removed tools

### ISSUE THREAD

**Issue by jmartisk** [quarkiverse/quarkus-langchain4j#1009]
If I declare some tools that are unused, and they get removed in the build, they are nevertheless still included in the metadata in the `ToolsRecorder`, so the Dev UI chat page still assumes they exist, and the constructor of the related JSON-RPC service fails when it tries to inject them:

```
2024-10-24 11:00:46,094 ERROR [io.qua.dev.run.jso.JsonRpcCodec] (executor-thread-2) Error in JsonRPC Call: jakarta.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [class io.quarkiverse.langchain4j.sample.chatbot.RemovedTools] and qualifiers [[]]
	at io.quarkus.arc.impl.InstanceImpl.bean(InstanceImpl.java:288)
	at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:309)
	at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:190)
	at io.quarkiverse.langchain4j.runtime.devui.ChatJsonRPCService.<init>(ChatJsonRPCService.java:106)
	at io.quarkiverse.langchain4j.runtime.devui.ChatJsonRPCService_Subclass.<init>(Unknown Source)
	at io.quarkiverse.langchain4j.runtime.devui.ChatJsonRPCService_Bean.doCreate(Unknown Source)
	at io.quarkiverse.langchain4j.runtime.devui.ChatJsonRPCService_Bean.create(Unknown Source)
	at io.quarkiverse.langchain4j.runtime.devui.ChatJsonRPCService_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c20(Unknown Source)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	at io.quarkiverse.langchain4j.runtime.devui.ChatJsonRPCService_ClientProxy.arc$delegate(Unknown Source)
	at io.quarkiverse.langchain4j.runtime.devui.ChatJsonRPCService_ClientProxy.isStreamingChatSupported(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.devui.runtime.comms.JsonRpcRouter.lambda$invoke$12(JsonRpcRouter.java:296)
	at io.smallrye.mutiny.unchecked.UncheckedSupplier.lambda$toSupplier$0(UncheckedSupplier.java:41)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:28)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1495)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

This leaves the chat page unusable

**Comment by jmartisk** [comment]
@geoand what should be the solution?

- option1: detect removed tools and not include them in `ToolsRecorder.setMetadata`, if that's possible
- option2: let the dev UI page just catch and ignore this exception

**Comment by geoand** [comment]
Ideally `1`. It's generally possible as Arc gives us this info, but there might be issues with build cycles
