### ISSUE TITLE
NPE on AiServiceMethodImplementationSupport 

### ISSUE THREAD

**Issue by shrikanthkr** [quarkiverse/quarkus-langchain4j#1108]
Facing an issue while following up with the workshop on quarkus langchain 4j. Instead of mvn am using gradle as my setup. 

```posh
13:22:13 ERROR traceId=, parentId=, spanId=, sampled= [io.qu.we.ne.ru.Endpoints] (vert.x-eventloop-thread-2) Unable to consume text message in @OnTextMessage callback: WebSocket connection [endpointId=com.spendflo.app.api.HelpDocAgentWebSocket, path=/help, id=0e6886c2-b047-4dfc-993c-5faf539ae23c]: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at io.quarkus.qute.TemplateInstanceBase.data(TemplateInstanceBase.java:45)
	at io.quarkiverse.langchain4j.QuarkusPromptTemplateFactory$QuteTemplate.render(QuarkusPromptTemplateFactory.java:67)
	at dev.langchain4j.model.input.PromptTemplate.apply(PromptTemplate.java:102)
	at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.prepareSystemMessage(AiServiceMethodImplementationSupport.java:572)
	at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.doImplement(AiServiceMethodImplementationSupport.java:147)
	at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.implement(AiServiceMethodImplementationSupport.java:129)
	at com.spendflo.app.agents.HelpdocAgent$$QuarkusImpl.userMessage(Unknown Source)
	at com.spendflo.app.agents.HelpdocAgent$$QuarkusImpl_ClientProxy.userMessage(Unknown Source)
	at com.spendflo.app.api.HelpDocAgentWebSocket.onTextMessage(HelpDocAgentWebSocket.java:28)
	at com.spendflo.app.api.HelpDocAgentWebSocket_WebSocketServerEndpoint.doOnTextMessage(Unknown Source)
	at io.quarkus.websockets.next.runtime.WebSocketEndpointBase.doExecute(WebSocketEndpointBase.java:174)
	at io.quarkus.websockets.next.runtime.WebSocketEndpointBase$1.run(WebSocketEndpointBase.java:111)
	at io.quarkus.websockets.next.runtime.ConcurrencyLimiter.run(ConcurrencyLimiter.java:53)
	at io.quarkus.websockets.next.runtime.WebSocketEndpointBase.execute(WebSocketEndpointBase.java:108)
	at io.quarkus.websockets.next.runtime.WebSocketEndpointBase.onTextMessage(WebSocketEndpointBase.java:76)
	at io.quarkus.websockets.next.runtime.Endpoints.lambda$initialize$1(Endpoints.java:122)
	at io.quarkus.websockets.next.runtime.Endpoints$5$1.handle(Endpoints.java:335)
	at io.quarkus.websockets.next.runtime.Endpoints$5$1.handle(Endpoints.java:332)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:252)
	at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:50)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

HelpDoc Agent code. I have just renamed it from CustomerSuccessAgent

```java
@SessionScoped
@RegisterAiService
public interface HelpdocAgent {

    @SystemMessage("""
            You are customer success agent, who guides the customer to take actions.
            If the question is unrelated to user guide, ignore them.
            """)
    @InputGuardrails(PromptInjectionGuard.class)
    Multi<String> userMessage(String userMessage);
}

```

PromptInjectionGuard

```java
@ApplicationScoped
class PromptInjectionGuard implements InputGuardrail {

    private final PromptInjectionDetectionAgent service;

    public PromptInjectionGuard(PromptInjectionDetectionAgent service) {
        this.service = service;
    }

    @Override
    public InputGuardrailResult validate(UserMessage userMessage) {
        double result = service.isInjection(userMessage.singleText());
        if (result > 0.7) {
            return failure("Prompt injection detected");
        }
        return success();
    }
}
```

PromptInjectionDetectionAgent is exactly the same as in workshop sample. Could you please guide me where am I going wrong? 

**More Details:**
Java Version - 21
Build Tool - Gradle
Multi Module Quarkus App

**Comment by geoand** [comment]
Thanks for reporting!

Can you please attach the project you are using as a zip so we can run it and see the problem in action?

**Comment by shrikanthkr** [comment]
[issue_npe.zip](https://github.com/user-attachments/files/17918557/issue_npe.zip)
Attached a sample which can reproduce the same. 

I don't have a separate client, please use http://localhost:3002/q/dev-ui/io.quarkus.quarkus-websockets-next/server-endpoints to test it out.

**Comment by geoand** [comment]
The issue is that your Gradle configuration is missing the `-parameters` option for the Java compilation task. 
We normally have a warning for that, but you fell into a corner case where the warning wasn't displayed. 

https://github.com/quarkiverse/quarkus-langchain4j/pull/1113 fixes that

**Comment by shrikanthkr** [comment]
Could you elaborate on what parameters I should add?

**Comment by geoand** [comment]
Something like":

```gradle
tasks.withType<JavaCompile> {
    options.compilerArgs.add("-parameters")
}
```

should do the trick

**Comment by shrikanthkr** [comment]
oh! Damn thank you. I will give it a try. I assumed I have to add a specific parameter to solve for this

**Comment by geoand** [comment]
🙏🏽

**Comment by geoand** [comment]
👍🏽
