### ISSUE TITLE
Upgrading 0.21.0 -> 0.22.0 causes failures

### ISSUE THREAD

**Issue by edeandrea** [quarkiverse/quarkus-langchain4j#1129]
I have an app where it is [trying to upgrade](https://github.com/rh-rad-ai-roadshow/parasol-insurance/pull/175) from `0.21.0` to `0.22.0` and it fails with the following exception(s) (see https://github.com/rh-rad-ai-roadshow/parasol-insurance/actions/runs/12091388401/job/33800581449 & https://github.com/rh-rad-ai-roadshow/parasol-insurance/actions/runs/12091388401/job/33800581949

To reproduce, check out that PR and do `cd app && ./mvnw clean verify -Pollama` or `cd app && ./mvnw clean verify -Pjlama`

```
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 3, Time elapsed: 6.503 s <<< FAILURE! -- in org.parasol.resources.ClaimResourceTests
[ERROR] org.parasol.resources.ClaimResourceTests.getAllNoneFound -- Time elapsed: 0.004 s <<< ERROR!
java.lang.RuntimeException: 
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.SyntheticBeansProcessor#initRuntime threw an exception: java.lang.IllegalStateException: A synthetic bean with identifier OfFfdXYI2wr9Ymzsx9IXE32kX_M is already registered: SYNTHETIC bean [types=[dev.langchain4j.model.embedding.EmbeddingModel, java.lang.Object], qualifiers=[@Default, @Any], target=n/a]
        at io.quarkus.arc.processor.BeanDeployment.addSyntheticBean(BeanDeployment.java:1536)
        at io.quarkus.arc.processor.BeanDeployment$BeanRegistrationContextImpl.accept(BeanDeployment.java:1891)
        at io.quarkus.arc.processor.BeanDeployment$BeanRegistrationContextImpl.accept(BeanDeployment.java:1860)
        at io.quarkus.arc.processor.BeanConfigurator.done(BeanConfigurator.java:115)
        at io.quarkus.arc.deployment.SyntheticBeansProcessor.configureSyntheticBean(SyntheticBeansProcessor.java:101)
        at io.quarkus.arc.deployment.SyntheticBeansProcessor.initRuntime(SyntheticBeansProcessor.java:60)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
        at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:499)

        at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:628)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:712)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.SyntheticBeansProcessor#initRuntime threw an exception: java.lang.IllegalStateException: A synthetic bean with identifier OfFfdXYI2wr9Ymzsx9IXE32kX_M is already registered: SYNTHETIC bean [types=[dev.langchain4j.model.embedding.EmbeddingModel, java.lang.Object], qualifiers=[@Default, @Any], target=n/a]
        at io.quarkus.arc.processor.BeanDeployment.addSyntheticBean(BeanDeployment.java:1536)
        at io.quarkus.arc.processor.BeanDeployment$BeanRegistrationContextImpl.accept(BeanDeployment.java:1891)
        at io.quarkus.arc.processor.BeanDeployment$BeanRegistrationContextImpl.accept(BeanDeployment.java:1860)
        at io.quarkus.arc.processor.BeanConfigurator.done(BeanConfigurator.java:115)
        at io.quarkus.arc.deployment.SyntheticBeansProcessor.configureSyntheticBean(SyntheticBeansProcessor.java:101)
        at io.quarkus.arc.deployment.SyntheticBeansProcessor.initRuntime(SyntheticBeansProcessor.java:60)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
        at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:499)

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:355)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:272)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:62)
        at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:212)
        at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:595)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:645)
        ... 1 more
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.SyntheticBeansProcessor#initRuntime threw an exception: java.lang.IllegalStateException: A synthetic bean with identifier OfFfdXYI2wr9Ymzsx9IXE32kX_M is already registered: SYNTHETIC bean [types=[dev.langchain4j.model.embedding.EmbeddingModel, java.lang.Object], qualifiers=[@Default, @Any], target=n/a]
        at io.quarkus.arc.processor.BeanDeployment.addSyntheticBean(BeanDeployment.java:1536)
        at io.quarkus.arc.processor.BeanDeployment$BeanRegistrationContextImpl.accept(BeanDeployment.java:1891)
        at io.quarkus.arc.processor.BeanDeployment$BeanRegistrationContextImpl.accept(BeanDeployment.java:1860)
        at io.quarkus.arc.processor.BeanConfigurator.done(BeanConfigurator.java:115)
        at io.quarkus.arc.deployment.SyntheticBeansProcessor.configureSyntheticBean(SyntheticBeansProcessor.java:101)
        at io.quarkus.arc.deployment.SyntheticBeansProcessor.initRuntime(SyntheticBeansProcessor.java:60)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
        at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:499)

        at io.quarkus.builder.Execution.run(Execution.java:124)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:161)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:351)
        ... 6 more
Caused by: java.lang.IllegalStateException: A synthetic bean with identifier OfFfdXYI2wr9Ymzsx9IXE32kX_M is already registered: SYNTHETIC bean [types=[dev.langchain4j.model.embedding.EmbeddingModel, java.lang.Object], qualifiers=[@Default, @Any], target=n/a]
        at io.quarkus.arc.processor.BeanDeployment.addSyntheticBean(BeanDeployment.java:1536)
        at io.quarkus.arc.processor.BeanDeployment$BeanRegistrationContextImpl.accept(BeanDeployment.java:1891)
        at io.quarkus.arc.processor.BeanDeployment$BeanRegistrationContextImpl.accept(BeanDeployment.java:1860)
        at io.quarkus.arc.processor.BeanConfigurator.done(BeanConfigurator.java:115)
        at io.quarkus.arc.deployment.SyntheticBeansProcessor.configureSyntheticBean(SyntheticBeansProcessor.java:101)
        at io.quarkus.arc.deployment.SyntheticBeansProcessor.initRuntime(SyntheticBeansProcessor.java:60)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
        at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:499)
```

**Comment by edeandrea** [comment]
i scratched my head for a bit and nothing immediately obvious jumped out at me.

**Comment by jmartisk** [comment]
My guess would be that it may have something to do with https://github.com/quarkiverse/quarkus-langchain4j/commit/b1c52cbbb667ed86fc31c7478c53015d6fd99b6f because the app doesn't explicitly use any embedding models AFAICS

**Comment by edeandrea** [comment]
It actually does us an embedding model...It uses the easy rag extension. There are separate maven profiles that add the appropriate dependency (Ollama vs Jlama). If you don't use a profile you have the openai model.

**Comment by jmartisk** [comment]
Maybe the problem is that the configuration in the `prod` profile contains configs for all of {ollama,openai,jlama} and they reference the same logical model name `parasol-chat` (https://github.com/rh-rad-ai-roadshow/parasol-insurance/blob/main/app/src/main/resources/application.properties#L8), so maybe you have to only enable a set of properties for a single provider, because they clash otherwise?

**Comment by edeandrea** [comment]
Isn't that exactly what I'm doing?

https://github.com/rh-rad-ai-roadshow/parasol-insurance/blob/private-docs-rag-solution/app/src/main/resources/application.properties#L32-L33

https://github.com/rh-rad-ai-roadshow/parasol-insurance/blob/private-docs-rag-solution/app/src/main/resources/application.properties#L43-L44

In the profiles I'm telling which provider to use....All which worked fine until 0.22.0....

**Comment by jmartisk** [comment]
But the `quarkus.langchain4j.openai.parasol-chat.*` properties are present even when you activate the ollama/jlama profile, and so is the openai extension (you don't exclude it AFAICS in the pom), so they don't get ignored

Anyway I'm just wildly guessing here, I've already closed my work laptop for today.

**Comment by jmartisk** [comment]
The `BeansProcessor` now tries to register the same embedding model twice because Easy RAG now auto-registers it (https://github.com/quarkiverse/quarkus-langchain4j/blob/bb5c7227dc66d41f87825d7ba99d465612d30826/core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/BeansProcessor.java#L268), but the new logic that registers models regardless of them being used doesn't know about it, and generates the same `SelectedEmbeddingModelCandidateBuildItem` again (see https://github.com/quarkiverse/quarkus-langchain4j/blob/bb5c7227dc66d41f87825d7ba99d465612d30826/core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/BeansProcessor.java#L354)

I'm guessing the proper solution then should be that the embedding model for Easy RAG should be registered only if the user didn't choose a provider (because if they did, it the new logic will register it), but let me try it

**Comment by jmartisk** [comment]
I'd love to test the change, but your project suddenly just always fails with

```
Error in Quinoa while running package manager build command: node /home/jmartisk/Workspace/parasol-insurance/app/.quinoa/node/node_modules/npm/bin/npm-cli.js run build
```

(it worked 10 minutes ago...)
I'll send a PR and let you test it yourself :laughing:

**Comment by edeandrea** [comment]
> I'll send a PR and let you test it yourself 

Thats the open source way! :D

**Comment by edeandrea** [comment]
#1135 fixes this issue.
