### ISSUE TITLE
Upgrading from 0.21 to 0.22 runtime exception when Ingesting docs

### ISSUE THREAD

**Issue by lordofthejars** [quarkiverse/quarkus-langchain4j#1134]
Upgrading from 0.21 to 0.22 runtime exception when Ingesting docs. 
I have a simple project that works with 0.21 and fails when updated to 0.22 at runtime with a NoSuckMethod error.

The pom is:

```
<dependency>
            <groupId>io.quarkiverse.langchain4j</groupId>
            <artifactId>quarkus-langchain4j-openai</artifactId>
            <version>0.22.0</version>
        </dependency>
        <dependency>
            <groupId>io.quarkiverse.langchain4j</groupId>
            <artifactId>quarkus-langchain4j-chroma</artifactId>
            <version>0.22.0</version>
        </dependency>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-embeddings</artifactId>
            <version>0.34.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-embeddings-all-minilm-l6-v2-q</artifactId>
            <version>0.34.0</version>
            <scope>test</scope>
        </dependency>
```

See that langchain4j deps are in test scope.

The Ingestor code is:

```
@Inject
    ChromaEmbeddingStore store;

    @Inject
    EmbeddingModel embeddingModel;

    public void ingest(Path directory) throws IOException {
        List<Document> files;
        try (Stream<Path> streamFiles = Files.list(directory)) {
            final List<Document> documents = streamFiles
                .map(f -> loadDocument(f, new TextDocumentParser()))
                .toList();

            System.out.println(documents.size());

            files = new ArrayList<>(documents);
        }

        EmbeddingStoreIngestor ingestor = EmbeddingStoreIngestor.builder()
            .embeddingStore(store)
            .embeddingModel(embeddingModel)
            .documentSplitter(recursive(500, 0))
            .build();

        ingestor.ingest(files);
    }
```

When I run `quarkus dev` I got:

```
Caused by: java.lang.NoSuchMethodError: 'void dev.langchain4j.store.embedding.EmbeddingStoreIngestor.ingest(java.util.List)'
	at org.acme.ai.Ingestor.ingest(Ingestor.java:48)
	at org.acme.ai.Ingestor_ClientProxy.ingest(Unknown Source)
	at org.acme.GreetingResource.ingestDocuments(GreetingResource.java:22)
```

But only in 0.22, if I downgrade to 0.21 it works.

**Comment by geoand** [comment]
You can't use `quarkus-langchain4j` version `0.22` with upstream LangChain4j `0.34`, you need to use `0.36`

**Comment by lordofthejars** [comment]
But it is in test scope, is test scope added to quarkus dev?

**Comment by geoand** [comment]
It's not a matter of whether or not the dependency is added to the classpath, it's a matter of how it affects resolution of dependency versions.

In your case, it's should be easy enough to just update to the supported LangChain4j version and check

**Comment by lordofthejars** [comment]
Problem is that onnx embedded 0.36 doesn't work in intel mac. No worries.

**Comment by geoand** [comment]
👍🏽
