### ISSUE TITLE
Crash when defining own ChatMemoryStore bean

### ISSUE THREAD

**Issue by andreas-eberle** [quarkiverse/quarkus-langchain4j#158]
As soon as I add my own ChatMemoryStore implementation, the application crashes on startup with the following error:

```
2023-12-14 15:24:22,638 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-12-14 15:24:23,057 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.devui.ArcDevModeApiProcessor#collectBeanInfo threw an exception: java.lang.NullPointerException: Cannot invoke "io.quarkus.arc.deployment.devui.DevBeanInfo.getId()" because "node" is null
	at io.quarkus.arc.deployment.devui.DependencyGraph.filterLinks(DependencyGraph.java:37)
	at io.quarkus.arc.deployment.devui.ArcDevModeApiProcessor.collectBeanInfo(ArcDevModeApiProcessor.java:91)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: No bean type found for: CLASS bean [types=[com.arconsis.youtube.quarkus.langchain.services.ai.memory.MyMemoryStore, java.lang.Object, dev.langchain4j.store.memory.chat.ChatMemoryStore], qualifiers=[@Default, @Any], target=com.arconsis.youtube.quarkus.langchain.services.ai.memory.MyMemoryStore]
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:858)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: No bean type found for: CLASS bean [types=[com.arconsis.youtube.quarkus.langchain.services.ai.memory.MyMemoryStore, java.lang.Object, dev.langchain4j.store.memory.chat.ChatMemoryStore], qualifiers=[@Default, @Any], target=com.arconsis.youtube.quarkus.langchain.services.ai.memory.MyMemoryStore]
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.quarkus.arc.processor.BeanProcessor.generateResources(BeanProcessor.java:382)
	at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:519)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	... 6 more
```

This is the class I added
```
@ApplicationScoped
public class MyMemoryStore implements ChatMemoryStore {

    @Override
    public List<ChatMessage> getMessages(Object memoryId) {
        return List.of();
    }

    @Override
    public void updateMessages(Object memoryId, List<ChatMessage> messages) {
    }

    @Override
    public void deleteMessages(Object memoryId) {
    }
}
``` 

Here is a reproducer project:

[2023-12_quarkus-llms-java-reference.zip](https://github.com/quarkiverse/quarkus-langchain4j/files/13674577/2023-12_quarkus-llms-java-reference.zip)

**Comment by geoand** [comment]
https://github.com/quarkiverse/quarkus-langchain4j/pull/159 fixes the probme
