### ISSUE TITLE
Overriding EmbeddingModel throws ConfigurationException 

### ISSUE THREAD

**Issue by andreadimaio** [quarkiverse/quarkus-langchain4j#259]
I have created a new quarkus application that uses  the `quarkus-langchain4j-watsonx` module, which does not provide an implementation of the EmbeddingModel interface. So, to works with the RAG I have created a class to override the embedding business logic:
```java
@ApplicationScoped
public class CustomEmbeddingModel implements EmbeddingModel {

    @Override
    public Response<List<Embedding>> embedAll(List<TextSegment> textSegments) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'embedAll'");
    }    
}
```

but when I try to inject the EmbeddingModel interface I get the error:
```
Caused by: io.quarkus.runtime.configuration.ConfigurationException: A EmbeddingModel bean was requested, but no langchain4j providers were configured and no in-process embedding model were found on the classpath. Consider adding an extension like 'quarkus-langchain4j-openai' or one of the in-process embedding models.
        at io.quarkiverse.langchain4j.deployment.BeansProcessor.selectEmbeddingModelProvider(BeansProcessor.java:176)
        at io.quarkiverse.langchain4j.deployment.BeansProcessor.handleProviders(BeansProcessor.java:100)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

For more details there is a [zulip chat](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/.E2.9C.94.20Customize.20EmbeddingModel.20in.20quarkus-langchain4j).

**Comment by geoand** [comment]
Thanks for reporting.

I'll look into it tomorrow.
