### ISSUE TITLE
ChatCompletionRequest deserialization issue

### ISSUE THREAD

**Issue by fmatar** [quarkiverse/quarkus-langchain4j#296]
Issue with serializing / deserializing ChatCompletionRequest.

Here's the code:

```java
    @Test
     void serializationTest() {
        // Build the ChatCompletionRequest instance
        ChatCompletionRequest a = ChatCompletionRequest.builder()
          .messages(List.of(
              UserMessage.builder()
                .content("Write a short 1 paragraph funny poem about dynamic typing")
                .build()
            )
          ).temperature(0.8)
          .stream(false)
          .build(); 
        // Serialize the instance
        var encoded = Json.encode(a);
        // Deserialize the JSON back to a ChatCompletionRequest object
        var decoded = Json.decodeValue(encoded, ChatCompletionRequest.class);
        // Assert equality
        assertThat(decoded).isEqualTo(a);
    }
```

Looking at the available mixins for deserializing: [ChatCompletionRequestMixin.java](https://github.com/quarkiverse/quarkus-langchain4j/blob/main/openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/jackson/ChatCompletionRequestMixin.java 
)

I'm not sure this is even registered or getting triggered. 

Now the root issue lies in this implementation [ChatCompletionRequest.java](https://github.com/ai-for-java/openai4j/blob/main/src/main/java/dev/ai4j/openai4j/chat/ChatCompletionRequest.java)

My problem is simple, I want to deserialize a JSON string into a ChatCompletionRequestObject

**Comment by geoand** [comment]
What is the `Json` class you are using?

**Comment by fmatar** [comment]
I'm using `io.vertx.core.json.Json`

**Comment by geoand** [comment]
I although I am not sure what the use of such a test is, in any case you can use the  `dev.langchain4j.internal.Json` class which will include the properly configured mapper

**Comment by fmatar** [comment]
Here is a use case. I'm passing the whole ChatCompletionRequest to a REST endpoint among other properties. 

And here's a test case that illustrates the failure.

```
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

import ai.genfusion.core.persistence.BaseEntity;
import ai.genfusion.project.model.Project;
import dev.ai4j.openai4j.chat.ChatCompletionRequest;
import dev.langchain4j.internal.Json;
import io.quarkus.logging.Log;
import io.quarkus.test.junit.QuarkusTest;
import java.util.UUID;
import org.junit.jupiter.api.Test;

@QuarkusTest
class SerializationTest {


  @Test
  void test() {
    var a = ChatCompletionRequest.builder().stream(true).temperature(0.5).build();
    String json = Json.toJson(a);
    Log.info(STR."json: \{json}");

    var b = Json.fromJson(json, ChatCompletionRequest.class);
    assertThat(b, equalTo(a));
  }
}
```

This test fails with the following stack trace:

```
java.io.UncheckedIOException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `dev.ai4j.openai4j.chat.ChatCompletionRequest` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 2, column: 3]

	at io.quarkiverse.langchain4j.QuarkusJsonCodecFactory$Codec.fromJson(QuarkusJsonCodecFactory.java:52)
	at dev.langchain4j.internal.Json.fromJson(Json.java:79)
	at ai.genfusion.project.model.test.SerializationTest.test(SerializationTest.java:25)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:1013)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:827)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `dev.ai4j.openai4j.chat.ChatCompletionRequest` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 2, column: 3]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1887)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:414)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1375)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1508)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:348)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4899)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3846)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3814)
	at io.quarkiverse.langchain4j.QuarkusJsonCodecFactory$Codec.fromJson(QuarkusJsonCodecFactory.java:44)
	... 7 more

2024-02-15 04:13:02,985 INFO  [io.quarkus] (main) genfusion-api stopped in 0.090s
```

**Comment by fmatar** [comment]
Apologies for the delay, here's a [project](https://github.com/fmatar/quarkus-langchain4j-bug
) that shows the bug. 

The specific test case is this [one](https://github.com/fmatar/quarkus-langchain4j-bug/blob/main/src/test/java/com/acme/SerializationTest.java).

```
package com.acme;

import static org.hamcrest.CoreMatchers.equalToObject;
import static org.hamcrest.CoreMatchers.notNullValue;
import static org.hamcrest.MatcherAssert.assertThat;

import dev.ai4j.openai4j.chat.ChatCompletionRequest;
import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

@QuarkusTest
class SerializationTest {

  @Test
  void testSerializationWithLangchain4jSerialization() {
    var request = ChatCompletionRequest.builder().model("gpt-3.5-turbo").build();
    assertThat(request, notNullValue());
    var json = dev.langchain4j.internal.Json.toJson(request);
    assertThat(json, notNullValue());
    var deserialized = dev.langchain4j.internal.Json.fromJson(json, ChatCompletionRequest.class);
    assertThat(deserialized, equalToObject(request));
  }

  @Test
  void testSerializationWithQuarkusSerialization() {
    var request = ChatCompletionRequest.builder().model("gpt-3.5-turbo").build();
    assertThat(request, notNullValue());
    var json = io.vertx.core.json.Json.encode(request);
    assertThat(json, notNullValue());
    var deserialized = io.vertx.core.json.Json.decodeValue(json, ChatCompletionRequest.class);
    assertThat(deserialized, equalToObject(request));
  }
}
```

**Comment by geoand** [comment]
We have not added Jackson deserialization configuration because `ChatCompletionRequest` is never deserialized when using the API.
If you want to do the work of adding those mixins here, I'd be fine with that
