### ISSUE TITLE
Help needed for custom ChatMemoryStore

### ISSUE THREAD

**Issue by sebastienblanc** [quarkiverse/quarkus-langchain4j#361]
Hi !

I'm trying to implement a simple custom ChatMemoryStore that uses Redis, this is the implementation : 

```
package org.sebi;

import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.core.type.TypeReference;
import dev.langchain4j.data.message.ChatMessage;
import dev.langchain4j.store.memory.chat.ChatMemoryStore;
import io.quarkus.redis.datasource.RedisDataSource;
import io.quarkus.redis.datasource.keys.KeyCommands;
import io.quarkus.redis.datasource.value.ValueCommands;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.inject.Default;
import jakarta.inject.Inject;

@Default
@ApplicationScoped
public class RedisMemoryStore implements ChatMemoryStore{

    @Inject
    RedisDataSource redisDataSource;

    private final ValueCommands<String, List<ChatMessage>> valueCommands;
    private final KeyCommands<String> keyCommands;

    public RedisMemoryStore(RedisDataSource redisDataSource) {
            this.valueCommands = redisDataSource.value(new TypeReference<List<ChatMessage>>(){});
            this.keyCommands = redisDataSource.key();
    }

    @Override
    public List<ChatMessage> getMessages(Object memoryId) {
        if(keyCommands.exists(memoryId.toString())){
            return valueCommands.get(memoryId.toString());
        }
        {
            return new ArrayList<ChatMessage>();
        }
        
    }

    @Override
    public void updateMessages(Object memoryId, List<ChatMessage> messages) {
        valueCommands.set(memoryId.toString(), messages);
    }

    @Override
    public void deleteMessages(Object memoryId) {
        keyCommands.del(memoryId.toString());
    }
    
}
```

But I'm getting marshalling/unmarshalling issues like : 

```
2024-03-10 08:58:51,739 ERROR [io.qua.lan.run.ais.AiServiceMethodImplementationSupport] (executor-thread-1) Execution of org.sebi.MyAIService#chat failed: java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `dev.langchain4j.data.message.ChatMessage` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 2] (through reference chain: java.util.ArrayList[0])
        at io.quarkus.redis.datasource.codecs.Codecs$JsonCodec.decode(Codecs.java:86)
        at io.quarkus.redis.runtime.datasource.Marshaller.decode(Marshaller.java:97)
```
I think the right decoder amd mixins exists (by looking in the `core` extension) but I'm not sure on how to use it for my custom store. Any tips ?

**Comment by sebastienblanc** [comment]
I got it working with this custom codec but not really happy with `canHandle` implementation 😅 : 

```
import java.io.IOException;
import java.lang.reflect.Type;
import java.util.Collections;
import java.util.List;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;

import dev.langchain4j.data.message.ChatMessage;
import io.quarkiverse.langchain4j.QuarkusJsonCodecFactory;
import io.quarkus.redis.datasource.codecs.Codec;
import jakarta.enterprise.context.ApplicationScoped;

@ApplicationScoped
public class ChatMessageCodec implements Codec{
     private static final TypeReference<List<ChatMessage>> MESSAGE_LIST_TYPE = new TypeReference<>() {
        };
        
    @Override
    public boolean canHandle(Type clazz) {
        return true;
    }

    @Override
    public byte[] encode(Object item) {
       try {
            return QuarkusJsonCodecFactory.ObjectMapperHolder.MAPPER.writeValueAsString(item).getBytes();
    } catch (JsonProcessingException e) {
        throw new RuntimeException(e);
    }
    }

    @Override
    public Object decode(byte[] item) {
        if (item == null) {
                return Collections.emptyList();
            }
            try {
                return QuarkusJsonCodecFactory.ObjectMapperHolder.MAPPER.readValue(item, MESSAGE_LIST_TYPE);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
    }
    
}
```

**Comment by sebastienblanc** [comment]
Hum , that was easy in fact : 
```
    public boolean canHandle(Type clazz) {
        return MESSAGE_LIST_TYPE.getType().equals(clazz);
    }
```

**Comment by geoand** [comment]
So all good?

**Comment by sebastienblanc** [comment]
If it is the correct way to go then yes all good :)

**Comment by geoand** [comment]
It looks good to me :)
