### ISSUE TITLE
quarkus-langchain4j-ollama extension raises timeout exception

### ISSUE THREAD

**Issue by nicolasduminil** [quarkiverse/quarkus-langchain4j#398]
Using Quarkus 3.8.3 with the `quarkus-langchain4j-ollama` extension to expose an AI service. It randomly raises the following timeout exception:

    2024-03-21 17:42:09,862 ERROR [io.qua.lan.run.ais.AiServiceMethodImplementationSupport] (executor-thread-1)  Execution of fr.simplex_software.llm.haiku.HaikuService#answerMyQuestion failed: jakarta.ws.rs.ProcessingException: The timeout period of 10000ms has been exceeded while executing POST /api/generate for server null
    at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.unwrap(InvocationBuilderImpl.java:223)
    at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.method(InvocationBuilderImpl.java:339)
    at io.quarkiverse.langchain4j.ollama.OllamaRestApi$$QuarkusRestClientInterface.generate(Unknown Source)
    at io.quarkiverse.langchain4j.ollama.OllamaClient.completion(OllamaClient.java:35)
    at io.quarkiverse.langchain4j.ollama.OllamaChatLanguageModel.generate(OllamaChatLanguageModel.java:40)
    at  dev.langchain4j.model.chat.ChatLanguageModel_XNMsOaekknG7BdNZ5YSUkjh1SqE_Synthetic_ClientProxy.generate(Unknown Source)
    at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.doImplement(AiServiceMethodImplementationSupport.java:161)
    at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.implement(AiServiceMethodImplementationSupport.java:78)
    at fr.simplex_software.llm.haiku.HaikuService$$QuarkusImpl.answerMyQuestion(Unknown Source)
    at fr.simplex_software.llm.haiku.HaikuService$$QuarkusImpl_ClientProxy.answerMyQuestion(Unknown Source)
    at fr.simplex_software.llm.haiku.HaikuResource.answerAnyQuestion(HaikuResource.java:26)
    at fr.simplex_software.llm.haiku.HaikuResource$quarkusrestinvoker$answerAnyQuestion_9d73500961dba1becbad6cc8785d8b4564826544.invoke(Unknown Source)
    at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
    at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
    at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
    at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
    at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
    at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:840)
     Caused by: io.vertx.core.impl.NoStackTraceTimeoutException: The timeout period of 10000ms has been exceeded while executing POST /api/generate for server null

How could I increase the timeout ? I've tried to annotate with `@Timeout(25000)` the associated endpoint of the REST API calling the AI service but it still timeouts after 10000 ms, showing that the timeout comes from langchain4j and not from RESTeasy. However, if I modified the annotation to be `@Timeout(250)`, or in any case inferior to 10000 ms, then it's RESTeasy which timeouts.

**Comment by jmartisk** [comment]
That should be doable via a property like `quarkus.langchain4j.ollama.timeout=60s`

**Comment by geoand** [comment]
Have you tried `quarkus.langchain4j.openai.timeout=20s`

**Comment by nicolasduminil** [comment]
@jmartisk That was it, many thanks for your help and support.

**Comment by jmartisk** [comment]
@stonerich, no, `quarkus.langchain4j.ollama.timeout` didn't disappear. Are you saying it does not work properly for you?
