### ISSUE TITLE
NPE with websocket / converstation handling

### ISSUE THREAD

**Issue by cescoffier** [quarkiverse/quarkus-langchain4j#401]
```
2024-03-25 08:45:36,336 ERROR [io.und.web.request] (vert.x-eventloop-thread-2) UT026013: Unhandled error in annotated endpoint com.redhat.ChatBotWebSocket@c823ecd: java.lang.NullPointerException: Cannot invoke "java.util.Map.remove(Object)" because "this.chatMemories" is null
        at io.quarkiverse.langchain4j.runtime.aiservice.QuarkusAiServiceContext.removeChatMemoryIds(QuarkusAiServiceContext.java:48)
        at com.redhat.Bot$$QuarkusImpl.remove(Unknown Source)
        at io.quarkiverse.langchain4j.ChatMemoryRemover.remove(ChatMemoryRemover.java:28)
        at com.redhat.ChatBotWebSocket.onClose(ChatBotWebSocket.java:36)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.undertow.websockets.annotated.BoundMethod.invoke(BoundMethod.java:87)
```

**Comment by geoand** [comment]
Is this with the current latest release or `main`?

Asking because I recall fixing something similar.

**Comment by geoand** [comment]
I hope to get a new release out tomorrow or Wednesday

**Comment by geoand** [comment]
I have just released `0.10.0`. When you have some time, please give it a try and let me know if the issue has been fixed

**Comment by cescoffier** [comment]
Nope, still there:

```
redhat.ChatBotWebSocket@26599c5f: java.lang.NullPointerException: Cannot invoke "java.util.Map.remove(Object)" because "this.chatMemories" is null
        at io.quarkiverse.langchain4j.runtime.aiservice.QuarkusAiServiceContext.removeChatMemoryIds(QuarkusAiServiceContext.java:50)
        at com.redhat.Bot$$QuarkusImpl.remove(Unknown Source)
        at io.quarkiverse.langchain4j.ChatMemoryRemover.remove(ChatMemoryRemover.java:28)
        at com.redhat.ChatBotWebSocket.onClose(ChatBotWebSocket.java:36)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.undertow.websockets.annotated.BoundMethod.invoke(BoundMethod.java:87)
        at io.undertow.websockets.annotated.AnnotatedEndpoint$4.run(AnnotatedEndpoint.java:199)
```

Happens in dev mode when the websocket is cut during the hot reload.

**Comment by geoand** [comment]
Interesting, I'll make it more defensive

**Comment by geoand** [comment]
https://github.com/quarkiverse/quarkus-langchain4j/pull/408
