### ISSUE TITLE
Unable to use sentence-transformers/all-mpnet-base-v2 with HuggingFace

### ISSUE THREAD

**Issue by cescoffier** [quarkiverse/quarkus-langchain4j#50]
This embedding model is the default when using Python.

See: https://api.python.langchain.com/en/latest/embeddings/langchain.embeddings.huggingface.HuggingFaceEmbeddings.html

The exception is the following:

```
jakarta.ws.rs.ProcessingException: The timeout period of 10000ms has been exceeded while executing POST /pipeline/feature-extraction/sentence-transformers/all-mpnet-base-v2 for server api-inference.huggingface.co:443
        at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.unwrap(InvocationBuilderImpl.java:223)
        at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.method(InvocationBuilderImpl.java:344)
        at io.quarkiverse.langchain4j.huggingface.HuggingFaceRestApi$$QuarkusRestClientInterface.embed(Unknown Source)
        at io.quarkiverse.langchain4j.huggingface.QuarkusHuggingFaceClientFactory$QuarkusHuggingFaceClient.embed(QuarkusHuggingFaceClientFactory.java:84)
        at io.quarkiverse.langchain4j.huggingface.QuarkusHuggingFaceEmbeddingModel.embedTexts(QuarkusHuggingFaceEmbeddingModel.java:70)
        at io.quarkiverse.langchain4j.huggingface.QuarkusHuggingFaceEmbeddingModel.embedAll(QuarkusHuggingFaceEmbeddingModel.java:63)
        at dev.langchain4j.model.embedding.EmbeddingModel_39f15f757608db0afd626cecc7d217137da45ff3_Synthetic_ClientProxy.embedAll(Unknown Source)
        at dev.langchain4j.store.embedding.EmbeddingStoreIngestor.ingest(EmbeddingStoreIngestor.java:62)
        at io.quarkiverse.langchain4j.sample.openshift.ingestion.IngestionJob.run(IngestionJob.java:63)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:40)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.vertx.core.http.impl.NoStackTraceTimeoutException: The timeout period of 10000ms has been exceeded while executing POST /pipeline/feature-extraction/sentence-transformers/all-mpnet-base-v2 for server api-inference.huggingface.co:443
```

10s seems a lot for embedding computation.

**Comment by cescoffier** [comment]
Actually... no 10s was not enough....
