### ISSUE TITLE
SystemMessage too large.

### ISSUE THREAD

**Issue by fmatar** [quarkiverse/quarkus-langchain4j#635]
File too large to be in resources. 

I think this is more related to Quarkus itself than the langchain4j extension itself. 

I have place a file in my resources folder and the file is about 90kb of text. 

I haven't attempted to read it yet or do anything with it and Quarkus fails with the following exception:

```
io.vertx.core.impl.NoStackTraceException
Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.deployment.steps.MainClassBuildStep#build threw an exception: java.lang.RuntimeException: Failed to record call to method public void io.quarkiverse.langchain4j.runtime.AiServicesRecorder.setMetadata(java.util.Map)
	at io.quarkus.deployment.recording.BytecodeRecorderImpl.writeBytecode(BytecodeRecorderImpl.java:480)
	at io.quarkus.deployment.steps.MainClassBuildStep.writeRecordedBytecode(MainClassBuildStep.java:501)
	at io.quarkus.deployment.steps.MainClassBuildStep.build(MainClassBuildStep.java:201)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at java.base/java.lang.Thread.run(Thread.java:1570)
	at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: String too large to record: 
```

**Comment by geoand** [comment]
We should fix this, but I'll just note that using such a huge prompt as a system or user message is almost certainly not a good idea

**Comment by jmartisk** [comment]
Why is this being recorded at all, shouldn't the system message be overridable at runtime?

**Comment by fmatar** [comment]
I got around it by setting the SystemPrompt to a variable.
@SystemMessage="{system_prompt}"
```

And then in my @PostConstruct I'm setting the prompt as a global variable.

Not the usual approach for doing thing however this specific prompt is dictated by a massive schema definition.

**Comment by rsvoboda** [comment]
@fmatar do you have reproducer application that could be shared here?
