### ISSUE TITLE
Can't native compile using easy-rag

### ISSUE THREAD

**Issue by edeandrea** [quarkiverse/quarkus-langchain4j#644]
When using easy-rag I can't seem to compile to native. See https://github.com/edeandrea/quarkus-for-spring-devs-qa/actions/runs/9309155926/job/25624017837

```
[INFO] --- quarkus:3.11.0:build (default) @ quarkus-for-spring-devs-qa ---
Warning:  [io.quarkus.config] Unrecognized configuration key "quarkus.langchain4j.redis.dimension" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /home/runner/work/quarkus-for-spring-devs-qa/quarkus-for-spring-devs-qa/target/quarkus-for-spring-devs-qa-1.0-SNAPSHOT-native-image-source-jar/quarkus-for-spring-devs-qa-1.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /home/runner/work/quarkus-for-spring-devs-qa/quarkus-for-spring-devs-qa/target/quarkus-for-spring-devs-qa-1.0-SNAPSHOT-native-image-source-jar/quarkus-for-spring-devs-qa-1.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on MANDREL 23.1.2.0 JDK 21.0.2+13-LTS
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] /opt/hostedtoolcache/Java_jdkfile_jdk/21/x64/bin/native-image -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dlogging.initial-configurator.min-level=500 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Dfile.encoding=UTF-8 --features=io.quarkus.awt.runtime.graal.DarwinAwtFeature,io.quarkus.runner.Feature,io.quarkus.runtime.graal.DisableLoggingFeature,io.quarkus.hibernate.validator.runtime.DisableLoggingFeature,io.quarkiverse.poi.runtime.graal.POIFeature -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:+UnlockExperimentalVMOptions -H:BuildOutputJSONFile=quarkus-for-spring-devs-qa-1.0-SNAPSHOT-runner-build-output-stats.json -H:-UnlockExperimentalVMOptions --strict-image-heap -H:+UnlockExperimentalVMOptions -H:+AllowFoldMethods -H:-UnlockExperimentalVMOptions -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+UnlockExperimentalVMOptions -H:+ReportExceptionStackTraces -H:-UnlockExperimentalVMOptions -H:+AddAllCharsets --enable-url-protocols=http,https -H:NativeLinkerOption=-no-pie --enable-monitoring=heapdump -H:+UnlockExperimentalVMOptions -H:-UseServiceLoaderFeature -H:-UnlockExperimentalVMOptions -J--add-exports=org.graalvm.nativeimage/org.graalvm.nativeimage.impl=ALL-UNNAMED --exclude-config io\.netty\.netty-codec /META-INF/native-image/io\.netty/netty-codec/generated/handlers/reflect-config\.json --exclude-config io\.netty\.netty-handler /META-INF/native-image/io\.netty/netty-handler/generated/handlers/reflect-config\.json quarkus-for-spring-devs-qa-1.0-SNAPSHOT-runner -jar quarkus-for-spring-devs-qa-1.0-SNAPSHOT-runner.jar
Warning: The option '-H:ReflectionConfigurationResources=META-INF/native-image/ai/djl/api/reflect-config.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:ResourceConfigurationResources=META-INF/native-image/ai/djl/api/resource-config.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: Please re-evaluate whether any experimental option is required, and either remove or unlock it. The build output lists all active experimental options, including where they come from and possible alternatives. If you think an experimental option should be considered as stable, please file an issue.
========================================================================================================================
GraalVM Native Image: Generating 'quarkus-for-spring-devs-qa-1.0-SNAPSHOT-runner' (executable)...
========================================================================================================================
For detailed information and explanations on the build output, visit:
https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md
------------------------------------------------------------------------------------------------------------------------

[1/8] Initializing...                                                                                    (0.0s @ 0.29GB)
Error: Feature io.quarkus.awt.runtime.graal.DarwinAwtFeature class not found on the classpath. Ensure that the name is correct and that the class is on the classpath.
com.oracle.svm.core.util.UserError$UserException: Feature io.quarkus.awt.runtime.graal.DarwinAwtFeature class not found on the classpath. Ensure that the name is correct and that the class is on the classpath.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.registerFeatures(FeatureHandler.java:183)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:896)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:590)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:550)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:539)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:721)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:143)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:98)
------------------------------------------------------------------------------------------------------------------------
                        1.1s (11.9% of total time) in 39 GCs | Peak RSS: 0.89GB | CPU load: 3.60
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /home/runner/work/quarkus-for-spring-devs-qa/quarkus-for-spring-devs-qa/target/quarkus-for-spring-devs-qa-1.0-SNAPSHOT-native-image-source-jar/quarkus-for-spring-devs-qa-1.0-SNAPSHOT-runner-build-output-stats.json (build_info)
========================================================================================================================
Finished generating 'quarkus-for-spring-devs-qa-1.0-SNAPSHOT-runner' in 8.4s.
```

**Comment by geoand** [comment]
I am not surpsised to report that it works fine on Linux. 
This seems to be an issue in `quarkus-awt` - cc @Karm

**Comment by geoand** [comment]
Forget my comment above, I **can** reproduce this

**Comment by geoand** [comment]
This happens because you are manually excluding `quarkus-langchain4j-parsers-base`

**Comment by edeandrea** [comment]
Sounds good. Once #645 is released and I re-add the `quarkus-langchain4j-parsers-base` I will re-test and re-open if I still see the issue.

**Comment by geoand** [comment]
👌

**Comment by edeandrea** [comment]
I've confirmed that #645 fixes this after update to latest `quarkus-langchain4j`

**Comment by geoand** [comment]
Thanks for checking!
