### ISSUE TITLE
Random MismatchedInputException when using streaming with ollama

### ISSUE THREAD

**Issue by Malandril** [quarkiverse/quarkus-langchain4j#685]
# Context
When using Ollama with an AiService with streaming enabled i randomly get an exception, which causes the `Multi` to never close.
```java
HTTP 400 Bad Request
        at io.quarkus.rest.client.reactive.jackson.runtime.serialisers.ClientJacksonMessageBodyReader.readFrom(ClientJacksonMessageBodyReader.java:59)
        at org.jboss.resteasy.reactive.client.impl.ClientReaderInterceptorContextImpl.proceed(ClientReaderInterceptorContextImpl.java:86)
......
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `io.quarkiverse.langchain4j.ollama.ChatResponse` (although at least one Creator exists): no boolean/Boolean-argument constructor/factory method to deserialize from boolean value (true)
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1754)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1379)
        at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromBoolean(ValueInstantiator.java:371)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromBoolean(StdValueInstantiator.java:505)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromBoolean(BeanDeserializerBase.java:1651)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:206)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2125)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1501)
        at io.quarkus.rest.client.reactive.jackson.runtime.serialisers.ClientJacksonMessageBodyReader.readFrom(ClientJacksonMessageBodyReader.java:53)
        ... 46 more
```

This appears to happen more often when i run my Ollama  model on cpu.

I think it might be caused by `aroundReadFrom` returning `ChatResponse.emptyNotDone()` and trying another request after the end of the stream.
https://github.com/quarkiverse/quarkus-langchain4j/blob/32fcbc61a38cb15ae6e65da900794d30864688bc/model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaRestApi.java#L79

A naive working solution that i tested which removes the problem is adding the MismatchedInputException to the if in this method
```diff
-                if (e.getCause() instanceof JsonParseException) {
-                    if (e.getResponse().getStatus() == 200) {
+                if (e.getCause() instanceof JsonParseException || e.getCause() instanceof JsonMappingException) {
+                   if (e.getResponse().getStatus() == 200 || e.getResponse().getStatus() == 400) {
```

I don't know if it is a solution that makes sense, or if it would be better to try to fix the underlining problem.

**Comment by geoand** [comment]
Hi,

How can reproduce the proboem?

**Comment by geoand** [comment]
Closing for a lack of feedback.

If more information becomes available, feel free to add it and we can reexamine the issue.

**Comment by BenjaminRaimondi** [comment]
I have the same problem. 
In my case too, the exception thrown  is 400.
My problem occurs with local or remote ollama instance.
I will try to make a simple reproducer, in my case it happens every time.

**Comment by BenjaminRaimondi** [comment]
In https://github.com/quarkusio/quarkus/issues/44100 we can't see that the 200 or 400 code is rethrown be the ClientJackesonMessageBodyReader.
As you explain in your comment on OllamaRestApi.java @geoand : `This is needed because for some reason Vert. x is not giving us the entire content of the last chunk and this results in a json parsing exception.`
But does the potential bug in vertx cause only JsonParseException and not StreamReadException or DatabindException ?

**Comment by geoand** [comment]
> But does the potential bug in vertx cause only JsonParseException and not StreamReadException or DatabindException ?

If you can demonstrate that it does, then we can of course adapt the code :)

**Comment by jpohlmeyer** [comment]
I encountered the same problem and have a simple reproducer that (for me) reliably triggers the problem:
https://github.com/jpohlmeyer/quarkus-langchain4j-mismatchedinput-reproducer

The test cases using the Quarkus-Langchain4j implementation fail for me when using streaming mode with (at least) the models llama3.2:3b and gemma2:2b.

**Comment by geoand** [comment]
Thanks!

I'll have a look in the coming days

**Comment by geoand** [comment]
Thanks @jpohlmeyer! Using your reproducer I was able to come up with the proper fix:

https://github.com/quarkiverse/quarkus-langchain4j/pull/1070 handles

**Comment by jpohlmeyer** [comment]
Thanks for the quick fix @geoand!
From what i gathered we also have to adjust ClientJacksonMessageBodyReader (https://github.com/quarkusio/quarkus/blob/ea7996c7f2fb82e549dd79d21629648c87e0b9e2/extensions/resteasy-reactive/rest-client-jackson/runtime/src/main/java/io/quarkus/rest/client/reactive/jackson/runtime/serialisers/ClientJacksonMessageBodyReader.java#L53) to handle MismatchedInputException the same as JsonParseException or am i missing something?

**Comment by geoand** [comment]
You are welcome!

Unless you have a reproducer that shows a problem in action, I think not.

**Comment by jpohlmeyer** [comment]
I applied your fix on top of 0.21.0 and quarkusio/quarkus#44318 on top of 3.16.2 locally and then tried my reproducer test again. As I see it the MismatchedInputException is thrown directly and not wrapped in ClientWebApplicationException, thus can also not be unwrapped in the ClientWebApplicationException catch clause.

**Comment by geoand** [comment]
> As I see it the MismatchedInputException is thrown directly and not wrapped in ClientWebApplicationException, thus can also not be unwrapped in the ClientWebApplicationException catch clause.

You actually saw this in action?

**Comment by jpohlmeyer** [comment]
With just those too fixes applied my reproducer still fails for me locally. I cant say where the MismatchedInputException stems from originally, but it is not caught and handled in https://github.com/quarkiverse/quarkus-langchain4j/blob/8ad9c2666b2e4ae77cf9985531887d686dfcf15e/model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaRestApi.java#L88

**Comment by geoand** [comment]
Okay, feel free to add a new catch clause.

**Comment by jpohlmeyer** [comment]
I can add a PR, but am not quite sure what and where the best way to handle this is.
Adding the MismatchedInputException to the catch-clause in [ClientJacksonMessageBodyReader](https://github.com/quarkusio/quarkus/blob/ea7996c7f2fb82e549dd79d21629648c87e0b9e2/extensions/resteasy-reactive/rest-client-jackson/runtime/src/main/java/io/quarkus/rest/client/reactive/jackson/runtime/serialisers/ClientJacksonMessageBodyReader.java#L53) 
`} catch (JsonParseException | MismatchedInputException e) {`
solves the problem for me, but i don't know if this change makes sense in other contexts or breaks something somewhere else.

**Comment by jpohlmeyer** [comment]
Okay thanks for your feedback. I will try implementing a fix in `OllamaRestApi` then. It would probably be necessary to handle both cases (`MismatchedInputException` **not** wrapped in `ClientWebApplicationException` and `MismatchedInputException` wrapped in `ClientWebApplicationException` with Status 400) to make sure the fix works with Quarkus Versions that do not include the change quarkusio/quarkus#44318?

**Comment by geoand** [comment]
Yeah, exactly
