### ISSUE TITLE
Quarkus 3.12.1 vs quarkus-langchain4j 0.16.0

### ISSUE THREAD

**Issue by andreadimaio** [quarkiverse/quarkus-langchain4j#724]
When I try to use the latest version of quarkus in combination with `quarkus-langchain4j-watsonx` during the deploy phase, I get:

```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.langchain4j.watsonx.deployment.WatsonxProcessor#generateBeans threw an exception: java.lang.NoSuchFieldError: Class io.quarkiverse.langchain4j.deployment.LangChain4jDotNames does not have member field 'org.jboss.jandex.DotName TOKEN_COUNT_ESTIMATOR'
        at io.quarkiverse.langchain4j.watsonx.deployment.WatsonxProcessor.generateBeans(WatsonxProcessor.java:74)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1570)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:58)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:113)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:435)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:56)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.langchain4j.watsonx.deployment.WatsonxProcessor#generateBeans threw an exception: java.lang.NoSuchFieldError: Class io.quarkiverse.langchain4j.deployment.LangChain4jDotNames does not have member field 'org.jboss.jandex.DotName TOKEN_COUNT_ESTIMATOR'
        at io.quarkiverse.langchain4j.watsonx.deployment.WatsonxProcessor.generateBeans(WatsonxProcessor.java:74)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1570)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)

        at io.quarkus.builder.Execution.run(Execution.java:123)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:327)
        ... 9 more
Caused by: java.lang.NoSuchFieldError: Class io.quarkiverse.langchain4j.deployment.LangChain4jDotNames does not have member field 'org.jboss.jandex.DotName TOKEN_COUNT_ESTIMATOR'
        at io.quarkiverse.langchain4j.watsonx.deployment.WatsonxProcessor.generateBeans(WatsonxProcessor.java:74)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1570)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)

```

When I go back to Quarkus version `3.11.3` everything works fine.
Is there anything I need to change in the watsonx processor class?

**Comment by geoand** [comment]
Interesting ...I'll have to try this tomorrow

**Comment by geoand** [comment]
Are you sure you've cleaned everything and updated the Quarkus version properly (in both the dependencies and the maven plugin)?

**Comment by andreadimaio** [comment]
Maybe the `format c:` can help my machine?! :satisfied:

**Comment by andreadimaio** [comment]
The problem occurred after running a `quarkus update` with `999-SNAPSHOT`. I'll clean it up and try again.

**Comment by andreadimaio** [comment]
You were right, everything is working now. I close the issue.

**Comment by geoand** [comment]
Glad to hear it!
