### ISSUE TITLE
Upgrading 0.15.1 to 0.16.1 causes issues with micrometer

### ISSUE THREAD

**Issue by edeandrea** [quarkiverse/quarkus-langchain4j#731]
I have a pull request in the Quarkus superheroes that upgrades Quarkus Langchain4j from 0.15.1 to 0.16.1 and I'm getting all kinds of startup errors related to Micrometer.

See https://github.com/quarkusio/quarkus-super-heroes/actions/runs/9840344352/job/27164373444?pr=1069

```
[INFO] Running io.quarkus.sample.superheroes.narration.rest.AzureOpenAiNarrationResourceIT
Executing "/usr/lib/jvm/temurin-17-jdk-amd64/bin/java -Dquarkus.http.port=0 -Dquarkus.http.ssl-port=8444 -Dtest.url=http://0.0.0.0:0/ -Dquarkus.log.file.path=/home/runner/work/quarkus-super-heroes/quarkus-super-heroes/rest-narration/target/quarkus.log -Dquarkus.log.file.enable=true -Dquarkus.log.category."io.quarkus".level=INFO -Dquarkus.profile=azure-openai -Dquarkus.langchain4j.azure-openai.enable-integration=true -Dquarkus.wiremock.devservices.port=42405 -Dquarkus.langchain4j.azure-openai.endpoint=http://localhost:${quarkus.wiremock.devservices.port}/v1/ -Dquarkus.langchain4j.azure-openai.max-retries=2 -Dquarkus.langchain4j.azure-openai.log-requests=true -Dquarkus.test.arg-line= -Dquarkus.langchain4j.azure-openai.dalle3.enable-integration=true -Dquarkus.langchain4j.azure-openai.dalle3.timeout=3s -Dquarkus.langchain4j.azure-openai.dalle3.endpoint=http://localhost:${quarkus.wiremock.devservices.port}/v1/ -Dquarkus.langchain4j.azure-openai.timeout=3s -Dquarkus.configuration.build-time-mismatch-at-runtime=fail -Dquarkus.langchain4j.azure-openai.dalle3.max-retries=2 -Dquarkus.langchain4j.azure-openai.dalle3.log-responses=true -Dquarkus.http.host=0.0.0.0 -Dquarkus.langchain4j.azure-openai.dalle3.log-requests=true -Dquarkus.langchain4j.azure-openai.log-responses=true -jar /home/runner/work/quarkus-super-heroes/quarkus-super-heroes/rest-narration/target/quarkus-app/quarkus-run.jar"

   ___                   _                ____                        _
  / _ \ _   _  __ _ _ __| | ___   _ ___  / ___| _   _ _ __   ___ _ __| |__   ___ _ __ ___   ___  ___
 | | | | | | |/ _` | '__| |/ / | | / __| \___ \| | | | '_ \ / _ \ '__| '_ \ / _ \ '__/ _ \ / _ \/ __|
 | |_| | |_| | (_| | |  |   <| |_| \__ \  ___) | |_| | |_) |  __/ |  | | | |  __/ | | (_) |  __/\__ \
  \__\_\\__,_|\__,_|_|  |_|\_\\__,_|___/ |____/ \__,_| .__/ \___|_|  |_| |_|\___|_|  \___/ \___||___/
  _   _                      _   _                   |_|
 | \ | | __ _ _ __ _ __ __ _| |_(_) ___  _ __
 |  \| |/ _` | '__| '__/ _` | __| |/ _ \| '_ \
 | |\  | (_| | |  | | | (_| | |_| | (_) | | | |
 |_| \_|\__,_|_|  |_|  \__,_|\__|_|\___/|_| |_|


                                                                            Powered by Quarkus 3.12.1
13:17:12 WARN  [io.qu.config] (main) Unrecognized configuration key "quarkus.wiremock.devservices.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
13:17:12 WARN  [io.qu.config] (main) Unrecognized configuration key "quarkus.langchain4j.openai.dalle3.moderation-model.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
13:17:12 WARN  [io.qu.config] (main) Unrecognized configuration key "quarkus.wiremock.devservices.port" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
13:17:12 WARN  [io.qu.config] (main) Unrecognized configuration key "quarkus.langchain4j.azure-openai.dalle3.moderation-model.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
13:17:12 WARN  [io.qu.config] (main) Unrecognized configuration key "quarkus.langchain4j.azure-openai.dalle3.embedding-model.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
13:17:12 WARN  [io.qu.config] (main) Unrecognized configuration key "quarkus.langchain4j.openai.dalle3.embedding-model.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
13:17:13 ERROR [io.qu.ru.Application] (main) Failed to start application (with profile [azure-openai]): java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Application was not started: 2024-07-08 13:17:13,854 fv-az569-963 quarkus-run.jar[2470] ERROR [io.qua.run.Application] (main) Failed to start application (with profile [azure-openai]): java.lang.RuntimeException: Failed to start quarkus
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
Caused by: jakarta.enterprise.inject.CreationException: Error creating synthetic bean [tSnRrro_NAsDTXSgSzJKlqn1tMI]: jakarta.enterprise.inject.CreationException: Synthetic bean instance for io.quarkus.micrometer.runtime.binder.HttpBinderConfiguration not initialized yet: io_quarkus_micrometer_runtime_binder_HttpBinderConfiguration_ed52a13ec8122ca194e382508d73ec7220bb7732
	- a synthetic bean initialized during RUNTIME_INIT must not be accessed during STATIC_INIT
	- RUNTIME_INIT build steps that require access to synthetic beans initialized during RUNTIME_INIT should consume the SyntheticBeansRuntimeInitBuildItem
	at io.quarkus.micrometer.runtime.binder.HttpBinderConfiguration_tSnRrro_NAsDTXSgSzJKlqn1tMI_Synthetic_Bean.doCreate(Unknown Source)
	at io.quarkus.micrometer.runtime.binder.HttpBinderConfiguration_tSnRrro_NAsDTXSgSzJKlqn1tMI_Synthetic_Bean.create(Unknown Source)
	at io.quarkus.micrometer.runtime.binder.HttpBinderConfiguration_tSnRrro_NAsDTXSgSzJKlqn1tMI_Synthetic_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.ComputingCacheContextInstances.computeIfAbsent(ComputingCacheContextInstances.java:19)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at io.quarkus.micrometer.runtime.binder.HttpBinderConfiguration_tSnRrro_NAsDTXSgSzJKlqn1tMI_Synthetic_Bean.get(Unknown Source)
	at io.quarkus.micrometer.runtime.binder.HttpBinderConfiguration_tSnRrro_NAsDTXSgSzJKlqn1tMI_Synthetic_Bean.get(Unknown Source)
	at io.quarkus.micrometer.runtime.binder.RestClientMetricsFilter_Bean.doCreate(Unknown Source)
	at io.quarkus.micrometer.runtime.binder.RestClientMetricsFilter_Bean.create(Unknown Source)
	at io.quarkus.micrometer.runtime.binder.RestClientMetricsFilter_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.ComputingCacheContextInstances.computeIfAbsent(ComputingCacheContextInstances.java:19)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at io.quarkus.micrometer.runtime.binder.RestClientMetricsFilter_Bean.get(Unknown Source)
	at io.quarkus.micrometer.runtime.binder.RestClientMetricsFilter_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:559)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:539)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:572)
	at io.quarkus.arc.impl.ArcContainerImpl.instanceHandle(ArcContainerImpl.java:534)
	at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:294)
	at io.quarkus.rest.client.reactive.runtime.RestClientBuilderImpl.register(RestClientBuilderImpl.java:292)
	at io.quarkus.rest.client.reactive.runtime.RestClientBuilderImpl.build(RestClientBuilderImpl.java:408)
	at io.quarkus.rest.client.reactive.runtime.QuarkusRestClientBuilderImpl.build(QuarkusRestClientBuilderImpl.java:267)
	at io.quarkiverse.langchain4j.openai.QuarkusOpenAiClient$1.apply(QuarkusOpenAiClient.java:122)
	at io.quarkiverse.langchain4j.openai.QuarkusOpenAiClient$1.apply(QuarkusOpenAiClient.java:84)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
	at io.quarkiverse.langchain4j.openai.QuarkusOpenAiClient.<init>(QuarkusOpenAiClient.java:84)
	at io.quarkiverse.langchain4j.openai.QuarkusOpenAiClient$Builder.build(QuarkusOpenAiClient.java:555)
	at io.quarkiverse.langchain4j.azure.openai.AzureOpenAiChatModel.<init>(AzureOpenAiChatModel.java:91)
	at io.quarkiverse.langchain4j.azure.openai.AzureOpenAiChatModel$Builder.build(AzureOpenAiChatModel.java:284)
	at io.quarkiverse.langchain4j.azure.openai.runtime.AzureOpenAiRecorder.chatModel(AzureOpenAiRecorder.java:71)
	at io.quarkus.deployment.steps.AzureOpenAiProcessor$generateBeans295026147.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.AzureOpenAiProcessor$generateBeans295026147.deploy(Unknown Source)
	... 13 more
Caused by: jakarta.enterprise.inject.CreationException: Synthetic bean instance for io.quarkus.micrometer.runtime.binder.HttpBinderConfiguration not initialized yet: io_quarkus_micrometer_runtime_binder_HttpBinderConfiguration_ed52a13ec8122ca194e382508d73ec7220bb7732
	- a synthetic bean initialized during RUNTIME_INIT must not be accessed during STATIC_INIT
	- RUNTIME_INIT build steps that require access to synthetic beans initialized during RUNTIME_INIT should consume the SyntheticBeansRuntimeInitBuildItem
	at io.quarkus.micrometer.runtime.binder.HttpBinderConfiguration_tSnRrro_NAsDTXSgSzJKlqn1tMI_Synthetic_Bean.createSynthetic(Unknown Source)
	... 55 more

Failed to launch the application. The application logs can be found at: /home/runner/work/quarkus-super-heroes/quarkus-super-heroes/rest-narration/target/quarkus.log
Error:  Tests run: 7, Failures: 0, Errors: 1, Skipped: 6, Time elapsed: 9.730 s <<< FAILURE! -- in io.quarkus.sample.superheroes.narration.rest.AzureOpenAiNarrationResourceIT
Error:  io.quarkus.sample.superheroes.narration.rest.AzureOpenAiNarrationResourceIT.helloEndpoint -- Time elapsed: 0.010 s <<< ERROR!
java.lang.RuntimeException: java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.throwBootFailureException(QuarkusIntegrationTestExtension.java:373)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeEach(QuarkusIntegrationTestExtension.java:117)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
	at io.quarkus.test.common.LauncherUtil.waitForCapturedListeningData(LauncherUtil.java:102)
	at io.quarkus.test.common.DefaultJarLauncher.start(DefaultJarLauncher.java:72)
	at io.quarkus.test.junit.IntegrationTestUtil.startLauncher(IntegrationTestUtil.java:194)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.doProcessStart(QuarkusIntegrationTestExtension.java:301)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.ensureStarted(QuarkusIntegrationTestExtension.java:169)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeAll(QuarkusIntegrationTestExtension.java:130)
	... 1 more
```

**Comment by geoand** [comment]
So just updating for `0.15.1` to `0.16.1` and doing nothing else causes the problem?

**Comment by geoand** [comment]
FWIW, I **cannot** reproduce the problem.

**Comment by edeandrea** [comment]
```bash
export QUARKUS_PROFILE=azure-openai
export QUARKUS_TEST_INTEGRATION_TEST_PROFILE=azure-openai 
./mvnw clean verify

...

[INFO] --- failsafe:3.3.0:integration-test (default) @ rest-narration ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.quarkus.sample.superheroes.narration.rest.AzureOpenAiNarrationResourceIT
Executing "/Users/edeandre/.sdkman/candidates/java/21.0.3-tem/bin/java -Dquarkus.http.port=0 -Dquarkus.http.ssl-port=8444 -Dtest.url=http://localhost:0 -Dquarkus.log.file.path=/Users/edeandre/workspaces/quarkus/quarkus-super-heroes-main/rest-narration/target/quarkus.log -Dquarkus.log.file.enable=true -Dquarkus.log.category."io.quarkus".level=INFO -Dquarkus.profile=azure-openai -Dquarkus.langchain4j.azure-openai.enable-integration=true -Dquarkus.wiremock.devservices.port=53577 -Dquarkus.langchain4j.azure-openai.endpoint=http://localhost:${quarkus.wiremock.devservices.port}/v1/ -Dquarkus.langchain4j.azure-openai.max-retries=2 -Dquarkus.langchain4j.azure-openai.log-requests=true -Dquarkus.test.arg-line= -Dquarkus.langchain4j.azure-openai.dalle3.enable-integration=true -Dquarkus.langchain4j.azure-openai.dalle3.timeout=3s -Dquarkus.langchain4j.azure-openai.dalle3.endpoint=http://localhost:${quarkus.wiremock.devservices.port}/v1/ -Dquarkus.langchain4j.azure-openai.timeout=3s -Dquarkus.configuration.build-time-mismatch-at-runtime=fail -Dquarkus.langchain4j.azure-openai.dalle3.max-retries=2 -Dquarkus.langchain4j.azure-openai.dalle3.log-responses=true -Dquarkus.langchain4j.azure-openai.dalle3.log-requests=true -Dquarkus.langchain4j.azure-openai.log-responses=true -jar /Users/edeandre/workspaces/quarkus/quarkus-super-heroes-main/rest-narration/target/quarkus-app/quarkus-run.jar"

   ___                   _                ____                        _
  / _ \ _   _  __ _ _ __| | ___   _ ___  / ___| _   _ _ __   ___ _ __| |__   ___ _ __ ___   ___  ___
 | | | | | | |/ _` | '__| |/ / | | / __| \___ \| | | | '_ \ / _ \ '__| '_ \ / _ \ '__/ _ \ / _ \/ __|
 | |_| | |_| | (_| | |  |   <| |_| \__ \  ___) | |_| | |_) |  __/ |  | | | |  __/ | | (_) |  __/\__ \
  \__\_\\__,_|\__,_|_|  |_|\_\\__,_|___/ |____/ \__,_| .__/ \___|_|  |_| |_|\___|_|  \___/ \___||___/
  _   _                      _   _                   |_|
 | \ | | __ _ _ __ _ __ __ _| |_(_) ___  _ __
 |  \| |/ _` | '__| '__/ _` | __| |/ _ \| '_ \
 | |\  | (_| | |  | | | (_| | |_| | (_) | | | |
 |_| \_|\__,_|_|  |_|  \__,_|\__|_|\___/|_| |_|


                                                                            Powered by Quarkus 3.12.1
10:03:23 WARN  [io.qu.config] (main) Unrecognized configuration key "quarkus.wiremock.devservices.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
10:03:23 WARN  [io.qu.config] (main) Unrecognized configuration key "quarkus.langchain4j.openai.dalle3.moderation-model.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
10:03:23 WARN  [io.qu.config] (main) Unrecognized configuration key "quarkus.wiremock.devservices.port" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
10:03:23 WARN  [io.qu.config] (main) Unrecognized configuration key "quarkus.langchain4j.azure-openai.dalle3.moderation-model.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
10:03:23 WARN  [io.qu.config] (main) Unrecognized configuration key "quarkus.langchain4j.azure-openai.dalle3.embedding-model.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
10:03:23 WARN  [io.qu.config] (main) Unrecognized configuration key "quarkus.langchain4j.openai.dalle3.embedding-model.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
10:03:24 ERROR [io.qu.ru.Application] (main) Failed to start application (with profile [azure-openai]): java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
Caused by: jakarta.enterprise.inject.CreationException: Error creating synthetic bean [tSnRrro_NAsDTXSgSzJKlqn1tMI]: jakarta.enterprise.inject.CreationException: Synthetic bean instance for io.quarkus.micrometer.runtime.binder.HttpBinderConfiguration not initialized yet: io_quarkus_micrometer_runtime_binder_HttpBinderConfiguration_ed52a13ec8122ca194e382508d73ec7220bb7732
	- a synthetic bean initialized during RUNTIME_INIT must not be accessed during STATIC_INIT
	- RUNTIME_INIT build steps that require access to synthetic beans initialized during RUNTIME_INIT should consume the SyntheticBeansRuntimeInitBuildItem
	at io.quarkus.micrometer.runtime.binder.HttpBinderConfiguration_tSnRrro_NAsDTXSgSzJKlqn1tMI_Synthetic_Bean.doCreate(Unknown Source)
	at io.quarkus.micrometer.runtime.binder.HttpBinderConfiguration_tSnRrro_NAsDTXSgSzJKlqn1tMI_Synthetic_Bean.create(Unknown Source)
	at io.quarkus.micrometer.runtime.binder.HttpBinderConfiguration_tSnRrro_NAsDTXSgSzJKlqn1tMI_Synthetic_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.ComputingCacheContextInstances.computeIfAbsent(ComputingCacheContextInstances.java:19)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at io.quarkus.micrometer.runtime.binder.HttpBinderConfiguration_tSnRrro_NAsDTXSgSzJKlqn1tMI_Synthetic_Bean.get(Unknown Source)
	at io.quarkus.micrometer.runtime.binder.HttpBinderConfiguration_tSnRrro_NAsDTXSgSzJKlqn1tMI_Synthetic_Bean.get(Unknown Source)
	at io.quarkus.micrometer.runtime.binder.RestClientMetricsFilter_Bean.doCreate(Unknown Source)
	at io.quarkus.micrometer.runtime.binder.RestClientMetricsFilter_Bean.create(Unknown Source)
	at io.quarkus.micrometer.runtime.binder.RestClientMetricsFilter_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.ComputingCacheContextInstances.computeIfAbsent(ComputingCacheContextInstances.java:19)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at io.quarkus.micrometer.runtime.binder.RestClientMetricsFilter_Bean.get(Unknown Source)
	at io.quarkus.micrometer.runtime.binder.RestClientMetricsFilter_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:559)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:539)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:572)
	at io.quarkus.arc.impl.ArcContainerImpl.instanceHandle(ArcContainerImpl.java:534)
	at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:294)
	at io.quarkus.rest.client.reactive.runtime.RestClientBuilderImpl.register(RestClientBuilderImpl.java:292)
	at io.quarkus.rest.client.reactive.runtime.RestClientBuilderImpl.build(RestClientBuilderImpl.java:408)
	at io.quarkus.rest.client.reactive.runtime.QuarkusRestClientBuilderImpl.build(QuarkusRestClientBuilderImpl.java:267)
	at io.quarkiverse.langchain4j.openai.QuarkusOpenAiClient$1.apply(QuarkusOpenAiClient.java:122)
	at io.quarkiverse.langchain4j.openai.QuarkusOpenAiClient$1.apply(QuarkusOpenAiClient.java:84)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
	at io.quarkiverse.langchain4j.openai.QuarkusOpenAiClient.<init>(QuarkusOpenAiClient.java:84)
	at io.quarkiverse.langchain4j.openai.QuarkusOpenAiClient$Builder.build(QuarkusOpenAiClient.java:555)
	at io.quarkiverse.langchain4j.azure.openai.AzureOpenAiChatModel.<init>(AzureOpenAiChatModel.java:91)
	at io.quarkiverse.langchain4j.azure.openai.AzureOpenAiChatModel$Builder.build(AzureOpenAiChatModel.java:284)
	at io.quarkiverse.langchain4j.azure.openai.runtime.AzureOpenAiRecorder.chatModel(AzureOpenAiRecorder.java:71)
	at io.quarkus.deployment.steps.AzureOpenAiProcessor$generateBeans295026147.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.AzureOpenAiProcessor$generateBeans295026147.deploy(Unknown Source)
	... 11 more
Caused by: jakarta.enterprise.inject.CreationException: Synthetic bean instance for io.quarkus.micrometer.runtime.binder.HttpBinderConfiguration not initialized yet: io_quarkus_micrometer_runtime_binder_HttpBinderConfiguration_ed52a13ec8122ca194e382508d73ec7220bb7732
	- a synthetic bean initialized during RUNTIME_INIT must not be accessed during STATIC_INIT
	- RUNTIME_INIT build steps that require access to synthetic beans initialized during RUNTIME_INIT should consume the SyntheticBeansRuntimeInitBuildItem
	at io.quarkus.micrometer.runtime.binder.HttpBinderConfiguration_tSnRrro_NAsDTXSgSzJKlqn1tMI_Synthetic_Bean.createSynthetic(Unknown Source)
	... 53 more

Application was not started: 2024-07-08 10:03:24,130 edeandrea-m1pro quarkus-run.jar[64500] ERROR [io.qua.run.Application] (main) Failed to start application (with profile [azure-openai]): java.lang.RuntimeException: Failed to start quarkus
Failed to launch the application. The application logs can be found at: /Users/edeandre/workspaces/quarkus/quarkus-super-heroes-main/rest-narration/target/quarkus.log
[ERROR] Tests run: 7, Failures: 0, Errors: 1, Skipped: 6, Time elapsed: 6.508 s <<< FAILURE! -- in io.quarkus.sample.superheroes.narration.rest.AzureOpenAiNarrationResourceIT
[ERROR] io.quarkus.sample.superheroes.narration.rest.AzureOpenAiNarrationResourceIT.helloEndpoint -- Time elapsed: 0.005 s <<< ERROR!
java.lang.RuntimeException: java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.throwBootFailureException(QuarkusIntegrationTestExtension.java:373)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeEach(QuarkusIntegrationTestExtension.java:117)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
	at io.quarkus.test.common.LauncherUtil.waitForCapturedListeningData(LauncherUtil.java:102)
	at io.quarkus.test.common.DefaultJarLauncher.start(DefaultJarLauncher.java:72)
	at io.quarkus.test.junit.IntegrationTestUtil.startLauncher(IntegrationTestUtil.java:194)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.doProcessStart(QuarkusIntegrationTestExtension.java:301)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.ensureStarted(QuarkusIntegrationTestExtension.java:169)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeAll(QuarkusIntegrationTestExtension.java:130)
	... 1 more

[INFO] Running io.quarkus.sample.superheroes.narration.rest.OpenAiNarrationResourceIT
[WARNING] Tests run: 7, Failures: 0, Errors: 0, Skipped: 7, Time elapsed: 0 s -- in io.quarkus.sample.superheroes.narration.rest.OpenAiNarrationResourceIT
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   AzureOpenAiNarrationResourceIT.helloEndpoint » Runtime java.lang.IllegalStateException: Unable to determine the status of the running process. See the above logs for details
[INFO] 
[ERROR] Tests run: 14, Failures: 0, Errors: 1, Skipped: 13
```

**Comment by edeandrea** [comment]
> So just updating for `0.15.1` to `0.16.1` and doing nothing else causes the problem?

Yes

**Comment by edeandrea** [comment]
i think i saw the problem with `0.16.0` too

**Comment by geoand** [comment]
@edeandrea #732 fixes it

**Comment by edeandrea** [comment]
Thanks!
