### ISSUE TITLE
[Question] How to get the WatsonxChatModel instance

### ISSUE THREAD

**Issue by andreadimaio** [quarkiverse/quarkus-langchain4j#755]
I need to access the `WatsonxChatModel` class to use some specific functionality that `watsonx.ai` provides to the developer.

Specifically, I need to call a rest api that returns a prompt stored in `watsonx.ai` that I would like to use as input of an `AiService'. This would allow me to use a prompt that can be updated and tested by an AI engineer without touching the backend during the dev phase.

Initially my idea was to find a way to integrate this feature into the library with a specific annotation, but this functionality is something that would only be used by `watsonx.ai` and would require a lot of changes touching different parts of the core module, so the quickest way could be to inject `ChatLanguageModel` and use `ClientProxy.unwrap` to have access to the `WatsonxChatModel` instance where I will add the methods I need.

This change will allow me to avoid rewriting the rest client.
Is this the right way to go? Or is it better to use another approach?

**Comment by geoand** [comment]
Is there anything preventing you from doing:

```java
@Inject WatsonxChatModel model;

public void doSomething() {
   // BEFORE
   var result = model.whatever(input);
   // AFTER
}

```

?

**Comment by geoand** [comment]
Gotcha, that's an easy fix

**Comment by geoand** [comment]
Thir requirement actually turns out to clash with the `TokenEstimator` feature as well as with the `DisabledChatLanguageModel`...

**Comment by geoand** [comment]
This is not the first time those two features conspire to make things more difficult than they should be.

I need to think about both of these features more.

**Comment by andreadimaio** [comment]
Next time I have to keep my hands in my pockets and not write code. 😅

**Comment by geoand** [comment]
😂.


The `DisabledChatModel` actually causes more problems 😃.

In reality, I'm pretty sure it's fixable if I spend a little extra time on it - hopefully tomorrow

**Comment by geoand** [comment]
@edeandrea the `DisabledChatLanguageModel` is holding CDI integration back because it forces us to use the lowest common denominator... 

Unless there is a really really compeling use case for it, I am leaning towards removing it altogether

**Comment by edeandrea** [comment]
There is a compelling use case to use it, hence why it's implemented in upstream LangChain4j.

From reading this thread it isn't clear to me what the problem with it is. 

I'm not sure what `Holding CDI integration back` or 

Can you elaborate?

**Comment by geoand** [comment]
> There is a compelling use case to use it, hence why it's implemented in upstream LangChain4j

I'm gonna need way more than that if I am going to keep it in.

This is the second time the feature has caused problems with CDI beans and in this case it's about being able to inject the implementation class instead of the interface

**Comment by edeandrea** [comment]
I still don't have a good grasp on what the problem actually is.

> This is the second time the feature has caused problems with CDI beans

Can you elaborate?

**Comment by edeandrea** [comment]
> I'm gonna need way more than that if I am going to keep it in.

I certainly can't tell you about its use "out in the wild". I have no metrics on that. I can tell you that I personally depend on that feature and it would be a problem for me if it was removed.

**Comment by edeandrea** [comment]
> I still don't have a good grasp on what the problem actually is.
> 
> > This is the second time the feature has caused problems with CDI beans
> 
> Can you elaborate?

After putting my thinking cap on (sorry its still early in the morning here and am just having my 1st cup of coffee) I think I understand the problem.

```java
@Inject WatsonxChatModel model;

public void doSomething() {
   // BEFORE
   var result = model.whatever(input);
   // AFTER
}
```

This should work perfectly fine if `quarkus.langchain4j.watsonx.enable-integration=true` (the default). 

If I understand it correctly, if `quarkus.langchain4j.watsonx.enable-integration=false`, then the above code would result in

```
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.quarkiverse.langchain4j.watsonx.WatsonxChatModel and qualifiers [@Default]
        - injection target: com.ibm.made.resource.AssistantResource#extractorClient
        - declared on CLASS bean [types=[com.ibm.made.resource.AssistantResource, java.lang.Object], qualifiers=[@Default, @Any], target=com.ibm.made.resource.AssistantResource]
        The following classes match by type, but have been skipped during discovery:
        - io.quarkiverse.langchain4j.watsonx.WatsonxChatModel has no bean defining annotation (scope, stereotype, etc.)


        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:519)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:642)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:317)
        ... 12 more
```

Does that accurately describe the problem?

**Comment by geoand** [comment]
> This should work perfectly fine if quarkus.langchain4j.watsonx.enable-integration=true (the default), shouldn't it?

That's what I'm saying, it doesn't. 

> Does that accurately describe the problem?

It does. But it the current behavior is antithetical to what is expected of CDI beans where you can inject the concrete type if you so prefer. I'm much more in favor of providing that then a feature we have no idea of it's usefulness in real life.

**Comment by geoand** [comment]
> One solution is what I wrote above, @Inject ChatLanguageModel model, ClientProxy.unwrap and after a cast to WatsonxChatModel

Which is way too much to expect of users to do just to get the concrete type.

**Comment by geoand** [comment]
Just to make more clear why the `enable-integration` feature causes so much pain on the implementation side, just take a look at  `AnthropicRecorder` and try to update the code of the `chatModel` method to return the concrete type (`AnthropicChatModel`)

**Comment by edeandrea** [comment]
> I'm much more in favor of providing that then a feature we have no idea of it's usefulness in real life.

But you're in favor of ripping out a feature that you have no idea of it's usefulness in real life?

> But it the current behavior is antithetical to what is expected of CDI beans where you can inject the concrete type if you so prefer

I agree. Can we put our thinking caps on and see if there is a solution around this? I'm not as experienced with what can be done with `BuildStep`s. Is it possible to make a `BuildStep` that is specific to a property? This would at least allow to have 2 separate `BuildSteps` that could produce different raw types.

The other thing I'm thinking about is what if we subclassed the model classes and overrode the methods. We could inject a `DisabledChatLanguageModel` into the models, which could then be delegated to. I could whip up a quick prototype of what I have in my head if interested. We could apply the same pattern to all of the models. Then we'd fix the CDI problem but still allow this feature.

**Comment by geoand** [comment]
> But you're in favor of ripping out a feature that you have no idea of it's usefulness in real life?

At this point of the lifecycle of the project, absolutely!

> Can we put our thinking caps on and see if there is a solution around this

What makes you think I haven't? This is the 2nd time I've encountered the same problem and have spent non trivial times on it each time. 

> Is it possible to make a BuildStep that is specific to a property's value as a condition to entering the BuildStep? This would at least allow to have 2 separate BuildSteps that could produce different raw types.

No

> The other thing I'm thinking about is what if we subclassed the model classes and overrode the methods

Try it with the antrhopic case I mentioned

**Comment by edeandrea** [comment]
> Try it with the antrhopic case I mentioned

Let me try to throw something together today. If it works for that use case it would be repeatable across all the models.

**Comment by geoand** [comment]
It works for Watsonx, I tried it yesterday. It doesn't work for Antrhopic

**Comment by edeandrea** [comment]
> It works for Watsonx, I tried it yesterday. It doesn't work for Antrhopic without a ton of nastiness

Let me play with it a bit today and see what I can come up with.

**Comment by edeandrea** [comment]
What I noticed, specifically for the Anthropic model, is that the builder doesn't have a `public` constructor, like the rest of the models do. It would be much easier to do what I'm thinking of doing if the builder had a `public` constructor.

What if I prototyped one of the other models (like the OpenAI one)? If it looked good and we wanted to apply it we'd need to have a change in upstream LangChain4j for the model builders that don't have `public` constructors.

**Comment by geoand** [comment]
Even if it does, you stil need to add a no-args constructor to satisfy Arc.

> What if I prototyped one of the other models (like the OpenAI one)

I've [already done](https://github.com/quarkiverse/quarkus-langchain4j/commit/0c199717a0cc7628636c6f079c1fd01ccd8f665b) that for Watsonx.
But if you make sure that the same process works for all the other models, then we can keep the feature

**Comment by edeandrea** [comment]
I think watsonx is different because we have our own model class in the extension. OpenAI/Anthropic/etc are different because we don't have our own class for the model and instead just use the upstream. 

If I can make my idea work for OpenAI then it should be repeatable for others

**Comment by edeandrea** [comment]
> I've [already done](https://github.com/quarkiverse/quarkus-langchain4j/commit/0c199717a0cc7628636c6f079c1fd01ccd8f665b) that for Watsonx.

My idea is slightly different than what you've done. Not sure yet if it'll pan out, but I'll spend some time on it today.

**Comment by edeandrea** [comment]
> Even if it does, you stil need to add a no-args constructor to satisfy Arc.

Why does it need to have a no-args constructor?  The `OpenAIChatModel` class does not have a no-args constructor.

**Comment by geoand** [comment]
Try to register the concrete type and you'll see

**Comment by edeandrea** [comment]
So I played around. I must be doing something wrong because I have an empty constructor but still get that error.

https://github.com/edeandrea/quarkus-langchain4j/commit/e13e9732ac64eda8bc800938ce7c1941dbabccc9

**Comment by geoand** [comment]
Your not helping your case of keeping the feature :laugh

**Comment by edeandrea** [comment]
Maybe I should have been more explicit. I was asking for help because I'm not as familiar with the synthetic bran stuff in the processor. I'm sure I'm doing something wrong but I don't know what it is. My class does have a default constructor.

**Comment by geoand** [comment]
https://github.com/quarkiverse/quarkus-langchain4j/tree/improve-beans-v2 gets around the problem. So the same approach needs to be implemented for the rest of the providers - while also making sure upstream LangChain4j has public constructors.

**Comment by edeandrea** [comment]
Ship it!

See I knew you had it in you! Just took some prodding :D

**Comment by geoand** [comment]
Maybe **I** should have been more explicit. I am not going to do anymore on it 😉. If the enable-integration feature is to remain, you're gonna have to put your weight behing it 💪🏼

**Comment by edeandrea** [comment]
you've practically done it in that branch, right? what is missing? Just applying it to some of the other providers?

**Comment by geoand** [comment]
> Just applying it to some of the other providers?

Exactly. But it will need at least a fix in Anthropic  upstream (I haven't checked others)

**Comment by edeandrea** [comment]
i can work on it a bit. I'm going to be at an offsite all next week though, so probably won't be able to complete until after that.

**Comment by geoand** [comment]
👍🏼

**Comment by geoand** [comment]
@edeandrea have you had a chance to look at this?

**Comment by edeandrea** [comment]
I have not. Been busy with other things. I'm leaving tomorrow for PTO for 2 weeks too, so most likely won't get to it until the end of the month.

**Comment by geoand** [comment]
You'll be uicky if I have not nuked the disabled thing by then 😆

**Comment by edeandrea** [comment]
C'mon man have some faith in me. Have I ever let you down?:)

**Comment by geoand** [comment]
What's what with keeping the faith **and** trolling at the same time?? 😆

**Comment by edeandrea** [comment]
Trolling is fine - just don't take any actions!

**Comment by geoand** [comment]
I don't know man, my finger is itchy on the trigger...

**Comment by andreadimaio** [comment]
@geoand it's up to you if you want to close this one.

**Comment by geoand** [comment]
We can leave it as is for now
