### ISSUE TITLE
InMemoryEmbedding store does not seem to be a bean

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkiverse/quarkus-langchain4j#767]
```
2024-07-22 18:24:02,309 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type dev.langchain4j.store.embedding.inmemory.InMemoryEmbeddingStore and qualifiers [@Default]
        - injection target: com.emmanuelbernard.bearllm.Ingestor#store
        - declared on CLASS bean [types=[com.emmanuelbernard.bearllm.Ingestor, java.lang.Object], qualifiers=[@Default, @Any], target=com.emmanuelbernard.bearllm.Ingestor]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1546)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:338)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:167)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:490)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1570)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type dev.langchain4j.store.embedding.inmemory.InMemoryEmbeddingStore and qualifiers [@Default]
        - injection target: com.emmanuelbernard.bearllm.Ingestor#store
        - declared on CLASS bean [types=[com.emmanuelbernard.bearllm.Ingestor, java.lang.Object], qualifiers=[@Default, @Any], target=com.emmanuelbernard.bearllm.Ingestor]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:519)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:642)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:323)
        ... 12 more

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:58)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:113)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:435)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:56)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type dev.langchain4j.store.embedding.inmemory.InMemoryEmbeddingStore and qualifiers [@Default]
        - injection target: com.emmanuelbernard.bearllm.Ingestor#store
        - declared on CLASS bean [types=[com.emmanuelbernard.bearllm.Ingestor, java.lang.Object], qualifiers=[@Default, @Any], target=com.emmanuelbernard.bearllm.Ingestor]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1546)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:338)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:167)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:490)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1570)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type dev.langchain4j.store.embedding.inmemory.InMemoryEmbeddingStore and qualifiers [@Default]
        - injection target: com.emmanuelbernard.bearllm.Ingestor#store
        - declared on CLASS bean [types=[com.emmanuelbernard.bearllm.Ingestor, java.lang.Object], qualifiers=[@Default, @Any], target=com.emmanuelbernard.bearllm.Ingestor]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:519)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:642)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:323)
        ... 12 more

        at io.quarkus.builder.Execution.run(Execution.java:123)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:327)
        ... 9 more
Caused by: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type dev.langchain4j.store.embedding.inmemory.InMemoryEmbeddingStore and qualifiers [@Default]
        - injection target: com.emmanuelbernard.bearllm.Ingestor#store
        - declared on CLASS bean [types=[com.emmanuelbernard.bearllm.Ingestor, java.lang.Object], qualifiers=[@Default, @Any], target=com.emmanuelbernard.bearllm.Ingestor]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1546)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:338)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:167)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:490)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1570)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type dev.langchain4j.store.embedding.inmemory.InMemoryEmbeddingStore and qualifiers [@Default]
        - injection target: com.emmanuelbernard.bearllm.Ingestor#store
        - declared on CLASS bean [types=[com.emmanuelbernard.bearllm.Ingestor, java.lang.Object], qualifiers=[@Default, @Any], target                                                                                                                          =com.emmanuelbernard.bearllm.Ingestor]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:519)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:642)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:323)
        ... 12 more

```

From

```
@ApplicationScoped
public class Ingestor {
    @Inject
    InMemoryEmbeddingStore store;

    @Inject
    EmbeddingModel embeddingModel;

    public void ingest(List<Document> documents) {
        EmbeddingStoreIngestor ingestor = EmbeddingStoreIngestor.builder()
                .embeddingStore(store)
                .embeddingModel(embeddingModel)
                //TODO adjust splitter to Markdown
                .documentSplitter(recursive(500, 0))
                .build();
        // Warning - this can take a long time...
        ingestor.ingest(documents);
    }
}
```

I did that because the Redis example seem to imply it works
https://docs.quarkiverse.io/quarkus-langchain4j/dev/retrievers.html

Adding this class "fixed" the problem

```
public class InMemoryEmbeddingStoreProvider {
    @Produces
    @ApplicationScoped
    public InMemoryEmbeddingStore create() {
        return new InMemoryEmbeddingStore<>();
    }
}
```

**Comment by emmanuelbernard** [comment]
Yeah I found that some useful things are currently only in easy-rag:
1. the embedding store (what's its shortname to differentiate it form say the Redis store, what property to disambiguate when both are in the classpath. Unless we offer a `quarkus-langchain4j-embeddingstore`. But to be honest,m we want a configuration based way to swap stores, models etc so different profiles can use different versions.
2. the `ApacheTikaDocumentParser`, I'm not 100% sure but I suspect it can be useful outside easy-rag

Compounded to that, when you add easy rag to the classpath, you then have to set it up (path etc), so you cannot use it as a simple dependency. It makes the easy rag to less easy rag a big wall. 

I wonder if we want to move these conversdations in Discussions as "Improve langchain4J integration". WDYT?

Emmanuel

**Comment by geoand** [comment]
> I wonder if we want to move these conversdations in Discussions as "Improve langchain4J integration". WDYT?

Makes sense!
