### ISSUE TITLE
[Question] JUnit with `@Nested`

### ISSUE THREAD

**Issue by andreadimaio** [quarkiverse/quarkus-langchain4j#801]
I'm trying to write some JUnit tests using the `@Nested` annotation, but during the startup I get an error:
```
mvn clean test -Dtest=PromptFormatterTest -Dsurefire.failIfNoSpecifiedTests=false


[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.ibm.langchain4j.watsonx.deployment.PromptFormatterTest
[INFO] Running com.ibm.langchain4j.watsonx.deployment.PromptFormatterTest$PromptFormatterOnTest
2024-07-31 17:36:04,256 INFO  [io.quarkus] (main) quarkus-langchain4j-watsonx-deployment 999-SNAPSHOT on JVM (powered by Quarkus 3.8.2) started in 0.299s. 
2024-07-31 17:36:04,258 INFO  [io.quarkus] (main) Profile test activated. 
2024-07-31 17:36:04,258 INFO  [io.quarkus] (main) Installed features: [cdi, langchain4j, langchain4j-watsonx, qute, rest-client-reactive, rest-client-reactive-jackson, smallrye-context-propagation, vertx]
2024-07-31 17:36:04,279 INFO  [io.quarkus] (main) quarkus-langchain4j-watsonx-deployment stopped in 0.016s
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.956 s <<< FAILURE! -- in com.ibm.langchain4j.watsonx.deployment.PromptFormatterTest$PromptFormatterOnTest
[ERROR] com.ibm.langchain4j.watsonx.deployment.PromptFormatterTest$PromptFormatterOnTest -- Time elapsed: 3.956 s <<< ERROR!
java.lang.RuntimeException: org.junit.jupiter.api.extension.TestInstantiationException: Failed to create test instance
        at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:709)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: org.junit.jupiter.api.extension.TestInstantiationException: Failed to create test instance
        at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:681)
        ... 2 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at io.quarkus.runner.bootstrap.RunningQuarkusApplicationImpl.instance(RunningQuarkusApplicationImpl.java:90)
        at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:673)
        ... 2 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.runner.bootstrap.RunningQuarkusApplicationImpl.instance(RunningQuarkusApplicationImpl.java:88)
        ... 3 more
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [class com.ibm.langchain4j.watsonx.deployment.PromptFormatterTest$PromptFormatterOnTest] and qualifiers [[]]
        at io.quarkus.arc.impl.InstanceImpl.bean(InstanceImpl.java:288)
        at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:309)
        at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:190)
        ... 5 more
``` 

This is the Java class:
```java
public class PromptFormatterTest {

    @ApplicationScoped
    @RegisterAiService
    public interface AiService {
        @SystemMessage("You are a poet")
        @UserMessage("""
                Write a poeam about {topic} of 10 lines
                """)
        public String poem(String topic);
    }

    @Nested
    class PromptFormatterOnTest extends WireMockAbstract {

        @RegisterExtension
        static QuarkusUnitTest unitTest = new QuarkusUnitTest()
                .overrideRuntimeConfigKey("quarkus.langchain4j.watsonx.base-url", WireMockUtil.URL_WATSONX_SERVER)
                .overrideRuntimeConfigKey("quarkus.langchain4j.watsonx.iam.base-url", WireMockUtil.URL_IAM_SERVER)
                .overrideRuntimeConfigKey("quarkus.langchain4j.watsonx.api-key", WireMockUtil.API_KEY)
                .overrideRuntimeConfigKey("quarkus.langchain4j.watsonx.project-id", WireMockUtil.PROJECT_ID)
                .overrideConfigKey("quarkus.langchain4j.watsonx.chat-model.prompt-formatter", "true")
                .setArchiveProducer(() -> ShrinkWrap.create(JavaArchive.class).addClasses(WireMockUtil.class, AiService.class));

        @Test
        void testPromptFormatter() throws Exception {
            assertEquals(true, true);
        }
    }
}
```

What am I doing wrong? If you want to try it yourself, you can clone this [repo](https://github.com/andreadimaio/quarkus-langchain4j/tree/prompt_formatter).

**Comment by andreadimaio** [comment]
What I'm trying to achieve is to have different QuarkusUnitTest with different properties

**Comment by geoand** [comment]
I am not sure if that works honestly.

I'll have to look closer tomorrow

**Comment by geoand** [comment]
We actually have some examples of `@Nested` in this repo, see [this](https://github.com/quarkiverse/quarkus-langchain4j/blob/b3bd6cfaf6e53038e96356fd6123240fb9b433e0/model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/ToolValidationTest.java#L22) and [this](https://github.com/quarkiverse/quarkus-langchain4j/blob/40bbca61cccac37fa3029e64e28b896c48aa5440/model-providers/bam/deployment/src/test/java/io/quarkiverse/langchain4j/bam/deployment/ResponseSchemaExceptionTest.java#L81).

Does that help at all?

**Comment by andreadimaio** [comment]
No, if the test throws an exception before the application starts (during the build phase), the `@Nested` works fine, but if I need to do some test after running the server, I have the problem. In any case this was just a curiosity, I can go ahead without using the `@Nested` annotation.

**Comment by geoand** [comment]
Yeah, so this is probably a bug in `QuarkusUnitTest` itself
