### ISSUE TITLE
Getting weird error on ubuntu when running tests

### ISSUE THREAD

**Issue by edeandrea** [quarkiverse/quarkus-langchain4j#823]
I'm trying to run the CI on GitHub actions with an ubuntu runner and am seeing the following. It works fine when running on my local machine (macOS).

Code: https://github.com/rh-rad-ai-roadshow/parasol-insurance/tree/private-docs-rag-solution
CI: https://github.com/rh-rad-ai-roadshow/parasol-insurance/blob/private-docs-rag-solution/.github/workflows/simple-build-test.yml

```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:634)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:718)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:305)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:248)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:601)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:651)
	... 1 more
Caused by: java.lang.UnsatisfiedLinkError: Native Library /home/runner/.djl.ai/tokenizers/0.15.0-0.26.0-linux-x86_64/libtokenizers.so already loaded in another classloader
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:167)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2025)
	at ai.djl.huggingface.tokenizers.jni.LibUtils.loadLibrary(LibUtils.java:76)
	at ai.djl.huggingface.tokenizers.jni.LibUtils.<clinit>(LibUtils.java:41)
	at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:173)
	at dev.langchain4j.model.embedding.onnx.HuggingFaceTokenizer.createFrom(HuggingFaceTokenizer.java:92)
	at dev.langchain4j.model.embedding.onnx.HuggingFaceTokenizer.<init>(HuggingFaceTokenizer.java:38)
	at io.quarkiverse.langchain4j.easyrag.runtime.EasyRagIngestor.ingestDocumentsFromFilesystem(EasyRagIngestor.java:81)
	at io.quarkiverse.langchain4j.easyrag.runtime.EasyRagIngestor.ingest(EasyRagIngestor.java:54)
	at io.quarkiverse.langchain4j.easyrag.runtime.EasyRagRecorder.ingest(EasyRagRecorder.java:42)
	at io.quarkus.deployment.steps.EasyRagProcessor$ingest784711507.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.EasyRagProcessor$ingest784711507.deploy(Unknown Source)
	... 8 more
```

**Comment by kdubois** [comment]
FYI it also works on my local machine with Fedora 40, so not necessarily related to it running in a Linux environment

**Comment by edeandrea** [comment]
Any thoughts on this one? Definitely weird, but still an issue nonetheless. Its preventing our CI from being able to run.

**Comment by geoand** [comment]
No idea here

**Comment by edeandrea** [comment]
Should I post this to upstream Langchain4j and see what they say?

**Comment by geoand** [comment]
Maybe @jmartisk has an idea

**Comment by edeandrea** [comment]
Seems to have resolved itself after updating some dependency versions (NOT Quarkus or langchain versions). Very odd.

I'll close for now and reopen if it appears again.

**Comment by geoand** [comment]
😎

**Comment by edeandrea** [comment]
Thanks for that @jmartisk !

To clarify, is it that I would just need to create the EmbeddingModel class directly in the `@BeforeAll` method, even if I don't use it directly in my tests?

The test class you pointed to - it looks like you are using the embedding model directly within the test class. In my case, I am in a test class annotated with `@QuarkusTest`, so my test class doesn't use any of the LangChain4j things directly in the class...

**Comment by edeandrea** [comment]
In my case too I'm not using the `AllMiniLmL6V2QuantizedEmbeddingModel`. I'm using `OllamaEmbeddingModel`.

**Comment by jmartisk** [comment]
Ok, so if you have multiple `QuarkusTest`s that use RAG, then they all will try to build their own instance of the tokenizer, but if the tests run in the same JVM, this will fail, because the class loader will be different every time. In that case, one workaround that I can think of is to force each test to run in a separate JVM by adding `<reuseForks>false</reuseForks>` to the configuration of maven-surefire-plugin.

**Comment by jmartisk** [comment]
We also do this in some places, like https://github.com/quarkiverse/quarkus-langchain4j/blob/0.20.0/embedding-stores/redis/deployment/pom.xml#L89

**Comment by edeandrea** [comment]
That doesn't seem to fix the issue. I'm still seeing it...

```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 57.22 s <<< FAILURE! -- in org.parasol.ui.ClaimsDetailPageTests
Error:  org.parasol.ui.ClaimsDetailPageTests.pageLoads -- Time elapsed: 0.001 s <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:634)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:718)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:305)
	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:248)
	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:601)
	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:651)
	... 1 more
Caused by: java.lang.UnsatisfiedLinkError: Native Library /home/runner/.djl.ai/tokenizers/0.19.1-0.28.0-linux-x86_64/libtokenizers.so already loaded in another classloader
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:167)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
	at java.base/java.lang.Runtime.load0(Runtime.java:852)
	at java.base/java.lang.System.load(System.java:2025)
	at ai.djl.huggingface.tokenizers.jni.LibUtils.loadLibrary(LibUtils.java:76)
	at ai.djl.huggingface.tokenizers.jni.LibUtils.<clinit>(LibUtils.java:41)
	at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:184)
	at dev.langchain4j.model.embedding.onnx.HuggingFaceTokenizer.createFrom(HuggingFaceTokenizer.java:92)
	at dev.langchain4j.model.embedding.onnx.HuggingFaceTokenizer.<init>(HuggingFaceTokenizer.java:38)
	at io.quarkiverse.langchain4j.easyrag.runtime.EasyRagIngestor.ingestDocumentsFromFilesystem(EasyRagIngestor.java:81)
	at io.quarkiverse.langchain4j.easyrag.runtime.EasyRagIngestor.ingest(EasyRagIngestor.java:54)
	at io.quarkiverse.langchain4j.easyrag.runtime.EasyRagRecorder.ingest(EasyRagRecorder.java:42)
	at io.quarkus.deployment.steps.EasyRagProcessor$ingest784711507.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.EasyRagProcessor$ingest784711507.deploy(Unknown Source)
	... 8 more
```

**Comment by jmartisk** [comment]
I tried your repo (https://github.com/rh-rad-ai-roadshow/parasol-insurance/tree/private-docs-rag-solution) and by adding reuseForks=false, I went from the state where

the first test fails with `java.net.UnknownHostException: parasol-embedding-aiworkshop.apps.cluster-mr4lx.sandbox121.opentlc.com` and all subsequent tests fail with `UnsatisfiedLinkError`

to the state where just all tests fail with `java.net.UnknownHostException: parasol-embedding-aiworkshop.apps.cluster-mr4lx.sandbox121.opentlc.com`

But I'm not able to progress it any further without access to the cluster :)

**Comment by jmartisk** [comment]
Any chance you can attach a debugger or something that prints the stack trace every time the JVM tries to load the native library (perhaps the `HuggingFaceTokenizer.createFrom` method would work...)?! I wonder if it happens in any other case beyond inside `EasyRagRecorder.ingest`....

**Comment by edeandrea** [comment]
It works fine on my laptop. I'm only seeing the issues on Ubuntu linux....

**Comment by jmartisk** [comment]
> > But I'm not able to progress it any further without access to the cluster :)
> 
> You just need Ollama running. Run ollama and then run `./mvnw clean verify -Dquarkus.profile=ollama -Dquarkus.test.profile=ollama,test -Dquarkus.test.integration-test-profile=ollama,prod`

That gives me something entirely different :( 

```
	[error]: Build step io.quarkiverse.langchain4j.deployment.devservice.DevServicesOllamaProcessor#handleModels threw an exception: java.lang.RuntimeException: Unexpected response code: 500 response body: {"error":"error loading model /usr/share/ollama/.ollama/models/blobs/sha256:dde5aa3fc5ffc17176b5e8bdc82f587b24b2678c6c66101bf7da77af9f7cc"}
```

something must be wrong with my ollama, dang it.

**Comment by edeandrea** [comment]
I'm running with Ollama 0.3.12

**Comment by dennysfredericci** [comment]
Hmm, this doesn't appear to be related to the operating system.

**Comment by dennysfredericci** [comment]
I have the same exception...

```
[ERROR] org.parasol.ui.ClaimsListPageTests.correctTable -- Time elapsed: 0.001 s <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:632)
        at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:716)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:305)
        at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:245)
        at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:599)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:649)
        ... 1 more
Caused by: java.lang.UnsatisfiedLinkError: Native Library /Users/dennysfredericci/.djl.ai/tokenizers/0.19.1-0.28.0-osx-x86_64/libtokenizers.dylib already loaded in another classloader
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:167)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2399)
        at java.base/java.lang.Runtime.load0(Runtime.java:852)
        at java.base/java.lang.System.load(System.java:2030)
        at ai.djl.huggingface.tokenizers.jni.LibUtils.loadLibrary(LibUtils.java:76)
        at ai.djl.huggingface.tokenizers.jni.LibUtils.<clinit>(LibUtils.java:41)
        at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:184)
        at dev.langchain4j.model.embedding.onnx.HuggingFaceTokenizer.createFrom(HuggingFaceTokenizer.java:92)
        at dev.langchain4j.model.embedding.onnx.HuggingFaceTokenizer.<init>(HuggingFaceTokenizer.java:38)
        at io.quarkiverse.langchain4j.easyrag.runtime.EasyRagIngestor.ingestDocumentsFromFilesystem(EasyRagIngestor.java:81)
        at io.quarkiverse.langchain4j.easyrag.runtime.EasyRagIngestor.ingest(EasyRagIngestor.java:54)
        at io.quarkiverse.langchain4j.easyrag.runtime.EasyRagRecorder.ingest(EasyRagRecorder.java:42)
        at io.quarkus.deployment.steps.EasyRagProcessor$ingest784711507.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.EasyRagProcessor$ingest784711507.deploy(Unknown Source)
        ... 8 more
```

Running a simple  ```./mvnw clean package``` and yes, that is because it doesn't use ollama. 

I came to the same conclusion as @jmartisk 

"
the first test fails with ```java.net.UnknownHostException: parasol-embedding-aiworkshop.apps.cluster-mr4lx.sandbox121.opentlc.com``` and all subsequent tests fail with ```UnsatisfiedLinkError```
"

You could consider disabling the easy rag for OpenAI and enabling it for Ollama. 🤷🏼‍♂️

**Comment by edeandrea** [comment]
I really can't disable it for OpenAI because the main use case for this particular app is to use OpenAI. The [README](https://github.com/rh-rad-ai-roadshow/parasol-insurance/blob/main/app/README.md) clearly states how you would run it locally (using Ollama) if you wanted to, but that is not the primary use case. Just a convenience :)

**Comment by edeandrea** [comment]
It does seem to be somewhat intermittent though. It is running fine at the moment (see https://github.com/rh-rad-ai-roadshow/parasol-insurance/actions/runs/11635289650/job/32404313896), but then all of a sudden it will stop working.

**Comment by edeandrea** [comment]
There isn't one that showcases this app in particular, but there was a 3-hour deep dive on LangChain4j and Quarkus that I did along with @cescoffier and @geoand 

https://devoxx.be/talk/java-meets-ai-build-llm-powered-apps-with-langchain4j/
