### ISSUE TITLE
Compile time check if chat memory is required

### ISSUE THREAD

**Issue by andreas-eberle** [quarkiverse/quarkus-langchain4j#86]
I just tried the example from the guide and forgot about adding the chat memory / chat memory provider. The code compiles and quarkusDev is starting but when I try to use it, it fails with 

```
Caused by: dev.langchain4j.exception.IllegalConfigurationException: Please set up chatMemory or chatMemoryProvider in order to use tools. A ChatMemory that can hold at least 3 messages is required for the tools to work properly. While the LLM can technically execute a tool without chat memory, if it only receives the result of the tool's execution without the initial message from the user, it won't interpret the result properly.
	at dev.langchain4j.exception.IllegalConfigurationException.illegalConfiguration(IllegalConfigurationException.java:12)
	at dev.langchain4j.service.AiServices.performBasicValidation(AiServices.java:325)
```

It would be great if the extension could detect this during build time to avoid having runtime issues.

**Comment by geoand** [comment]
https://github.com/quarkiverse/quarkus-langchain4j/pull/92 fixes the issue
