### ISSUE TITLE
No bean found for required type [interface dev.langchain4j.model.embedding.EmbeddingModel]

### ISSUE THREAD

**Issue by andreadimaio** [quarkiverse/quarkus-langchain4j#861]
Since version `0.17.0` the `EmbeddingModel` is not injected correctly.
If I downgrade to `0.16.4` the problem disappears. 

```xml
  <dependency>
            <groupId>io.quarkiverse.langchain4j</groupId>
            <artifactId>quarkus-langchain4j-watsonx</artifactId>
            <version>0.17.0</version>
        </dependency>
        <dependency>
            <groupId>io.quarkiverse.langchain4j</groupId>
            <artifactId>quarkus-langchain4j-milvus</artifactId>
            <version>0.17.0</version>
        </dependency>
   ...
```

```
2024-09-04 15:28:53,034 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:116)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
        at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
        at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 3 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
        ... 16 more
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [interface dev.langchain4j.model.embedding.EmbeddingModel] and qualifiers [[@jakarta.enterprise.inject.Default()]]
        at io.quarkus.arc.impl.InstanceImpl.bean(InstanceImpl.java:288)
        at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:309)
        at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:190)
        at io.quarkiverse.langchain4j.runtime.devui.EmbeddingStoreJsonRPCService.<init>(EmbeddingStoreJsonRPCService.java:25)
        at io.quarkiverse.langchain4j.runtime.devui.EmbeddingStoreJsonRPCService_ClientProxy.<init>(Unknown Source)
        at io.quarkiverse.langchain4j.runtime.devui.EmbeddingStoreJsonRPCService_Bean.proxy(Unknown Source)
        at io.quarkiverse.langchain4j.runtime.devui.EmbeddingStoreJsonRPCService_Bean.get(Unknown Source)
        at io.quarkiverse.langchain4j.runtime.devui.EmbeddingStoreJsonRPCService_Bean.get(Unknown Source)
        at io.quarkus.arc.impl.InstanceImpl.getBeanInstance(InstanceImpl.java:325)
        at io.quarkus.arc.impl.InstanceImpl.getInternal(InstanceImpl.java:309)
        at io.quarkus.arc.impl.InstanceImpl.get(InstanceImpl.java:190)
        at io.quarkus.devui.runtime.comms.JsonRpcRouter.populateJsonRPCRuntimeMethods(JsonRpcRouter.java:67)
        at io.quarkus.devui.runtime.comms.JsonRpcRouter_ClientProxy.populateJsonRPCRuntimeMethods(Unknown Source)
        at io.quarkus.devui.runtime.DevUIRecorder.createJsonRpcRouter(DevUIRecorder.java:52)
        at io.quarkus.deployment.steps.DevUIProcessor$createJsonRpcRouter1067343756.deploy_1(Unknown Source)
        at io.quarkus.deployment.steps.DevUIProcessor$createJsonRpcRouter1067343756.deploy(Unknown Source)
        ... 17 more
```

**Comment by gabriel-mauricioo** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by geoand** [comment]
cc @jmartisk

**Comment by jmartisk** [comment]
What embedding model are you using (which extension and how is it configured)?
One potentially related idea coming to my mind is that if you use an in-process embedding model and have specified its class name in configuration, these have changed their package names, so you have to update that.

**Comment by andreadimaio** [comment]
I'm using the embedding model provided by watsonx, but when I switch to openai I have the same problem.
One note, if I inject the `EmbeddingModel` somewhere in the code, the application runs.

**Comment by jmartisk** [comment]
Ok let me try to reproduce it

**Comment by gsmet** [comment]
Looks a lot like ArC removing the bean.

**Comment by jmartisk** [comment]
Yes @gsmet it seems you're right, but uhm,  I'm puzzled why it happens when the embedding model bean is declared unremovable: https://github.com/quarkiverse/quarkus-langchain4j/blob/0.17.0/model-providers/watsonx/deployment/src/main/java/io/quarkiverse/langchain4j/watsonx/deployment/WatsonxProcessor.java#L101

**Comment by jmartisk** [comment]
Hmm, actually if there's nothing requesting the bean to be created because the application isn't using it, then there is no reason to create it. So it doesn't get created at all and that's why the Dev UI JSON-RPC  service can't find it. 

But the logic currently is that we still try to create the JSON-RPC service because there is a CANDIDATE for an embedding model available, even though it's not picked up in the end. I remember I had some difficulties figuring out inside the `LangChain4jDevUIProcessor` whether an embedding model will really be used or not, because of dependencies between build items (here we still need to add beans to CDI, so I think we can't have a  look what beans were actually registered in it).

**Comment by jmartisk** [comment]
We can either figure out how to detect that the embedding model isn't picked up (and skip registering the dev UI page and json-rpc service), or we can let the json-rpc service be created without breaking the whole build, and throw errors only when the user tries to invoke it in the dev ui

**Comment by jmartisk** [comment]
Detecting whether there is a usable embedding model without being able to look at the final bean container is probably very tricky, so I'd probably go with the solution to still register the dev UI page and let it throw reasonable errors at runtime... If nobody objects.
