### ISSUE TITLE
Error logged twice in typical REST service

### ISSUE THREAD

**Issue by gsmet** [quarkiverse/quarkus-langchain4j#863]
My AI service execution was failing because of: https://github.com/quarkiverse/quarkus-langchain4j/pull/862

And I ended up with the error logged twice (see below).

I think we should remove the logging that happens here:
https://github.com/quarkiverse/quarkus-langchain4j/blob/ffc0c6962855fb30794d77cc5760b901d60785d7/core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java#L119-L126

given we throw the exception and it will be caught later.

First error:

```
2024-09-04 18:49:56,138 ERROR [io.qua.lan.run.ais.AiServiceMethodImplementationSupport] (executor-thread-1) Execution of io.quarkus.devoxx.MyAiService#findLabels failed

Exception in SimilarityResource.java:67
	   65      @Path("labels")
	   66      public String labels(@RestQuery String title, @RestQuery String body) throws JsonProcessingException {
	-> 67          return myAiService.findLabels(title, body);
	   68      }
	   69  

: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "value" is null
	at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.transformTemplateParamValue(AiServiceMethodImplementationSupport.java:575)
	at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.prepareUserMessage(AiServiceMethodImplementationSupport.java:517)
	at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.doImplement(AiServiceMethodImplementationSupport.java:132)
	at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.implement(AiServiceMethodImplementationSupport.java:113)
	at io.quarkus.devoxx.MyAiService$$QuarkusImpl.findLabels(Unknown Source)
	at io.quarkus.devoxx.MyAiService$$QuarkusImpl_ClientProxy.findLabels(Unknown Source)
	at io.quarkus.devoxx.SimilarityResource.labels(SimilarityResource.java:67)
	at io.quarkus.devoxx.SimilarityResource$quarkusrestinvoker$labels_f0f27e6d879329f44f365acb21a87190bc3e1636.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

And then:

```
2024-09-04 18:49:56,144 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /similarity/labels/?title=Hibernate%20ORM%20ignores%20my%20XML%20mapping failed, error id: d05392ea-4b97-45ad-aa3a-a7f3a60cf15e-1

Exception in SimilarityResource.java:67
	   65      @Path("labels")
	   66      public String labels(@RestQuery String title, @RestQuery String body) throws JsonProcessingException {
	-> 67          return myAiService.findLabels(title, body);
	   68      }
	   69  

: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "value" is null
	at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.transformTemplateParamValue(AiServiceMethodImplementationSupport.java:575)
	at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.prepareUserMessage(AiServiceMethodImplementationSupport.java:517)
	at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.doImplement(AiServiceMethodImplementationSupport.java:132)
	at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.implement(AiServiceMethodImplementationSupport.java:113)
	at io.quarkus.devoxx.MyAiService$$QuarkusImpl.findLabels(Unknown Source)
	at io.quarkus.devoxx.MyAiService$$QuarkusImpl_ClientProxy.findLabels(Unknown Source)
	at io.quarkus.devoxx.SimilarityResource.labels(SimilarityResource.java:67)
	at io.quarkus.devoxx.SimilarityResource$quarkusrestinvoker$labels_f0f27e6d879329f44f365acb21a87190bc3e1636.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by geoand** [comment]
Sure, that makes sense!
