### ISSUE TITLE
BGE Small 1.5 missing

### ISSUE THREAD

**Issue by cescoffier** [quarkiverse/quarkus-langchain4j#897]
The embedding model https://huggingface.co/BAAI/bge-small-en-v1.5 is not supported (while supported in langchain4j)

**Comment by geoand** [comment]
cc @jmartisk

**Comment by cescoffier** [comment]
Hum, adding BGE 1.5 breaks a few things because easy-rag has a transitive dependency on it, which means that we end up with multiple embedding models in the doc module.

**Comment by jmartisk** [comment]
Hm, I had no idea that Easy RAG depends on it, and I think we could maybe get rid of that. We depend on `dev.langchain4j:langchain4j-easy-rag` but AFAIK we actually only use Tika (`dev.langchain4j:langchain4j-document-parser-apache-tika`) from it, while it transitively brings in BGE as well.

**Comment by cescoffier** [comment]
@jmartisk I'm looking into it.

**Comment by cescoffier** [comment]
Damned... testing this is tricky, I've unsatisfied linking error because of the native library loaded in 2 different classloaders...

**Comment by jmartisk** [comment]
Ah yeah, the good old https://github.com/quarkiverse/quarkus-langchain4j/issues/823 - see my proposed workarounds there

**Comment by cescoffier** [comment]
Yeah, I had to move all the tests in the same test case :-(

**Comment by cescoffier** [comment]
@geoand Are the native test of the in process embedding running in native?

I just got a nice:

```

[ [ SegfaultHandler caught a segfault in thread 0x000000013ae04200 ] ]
siginfo: si_signo: 10, si_code: 1, si_addr: 0x0000000300000030 (heapBase + 48)

General purpose register values:
  R0  0x000000013ae04200 is a thread
  R1  0x00000001019ad890 points into AOT compiled code java.util.stream.IntPipeline$5$1.accept(IntPipeline.java)
  R2  0x0000000000000000
  R3  0x0000000000000098 is an unknown value
  R4  0x00006000039a0110 is an unknown value
  R5  0x0000000000000009 is an unknown value
  R6  0x0000000000000001 is an unknown value
  R7  0x0000000000501808 is an unknown value
  R8  0x0000000300000000 is the heap base
  R9  0x00000000e84d485b is an unknown value
  R10 0x000000030207a4b8 points into the image heap (writable primitives)
    is an object of type [B with length 256: 0x02 0x03 0x04 0x06 0x03 0x04 0x05 0x07 ...
  R11 0x0000000000000000
  R12 0x00000003246d9306 points into the image heap (read-only huge)
  R13 0x00000000000007fd is an unknown value
  R14 0x00000000e86d5057 is an unknown value
  R15 0x00000000e84d485b is an unknown value
  R16 0x00000000e8600000 is an unknown value
  R17 0x0000000000000057 is an unknown value
  R18 0x0000000000000000
  R19 0x000000013ae04200 is a thread
  R20 0x000000000000000a is an unknown value
  R21 0x000000000000000b is an unknown value
  R22 0x00000001019ad890 points into AOT compiled code java.util.stream.IntPipeline$5$1.accept(IntPipeline.java)
  R23 0x0000600003bb8ac0 is an unknown value
  R24 0x0000000000000003 is an unknown value
  R25 0x000000000000000a is an unknown value
  R26 0x0000000000000002 is an unknown value
  R27 0x00006000039a0110 is an unknown value
  R28 0x0000000000000009 is an unknown value
  R29 0x00000001701965a0 points into the stack for thread 0x000000013ae04200
  R30 0x0000000129ac9904 is an unknown value
  SP  0x0000000170196530 points into the stack for thread 0x000000013ae04200
  PC  0x00000001005932d8 points into AOT compiled code com.oracle.svm.core.jni.JNIJavaCallTrampolineHolder.varargsJavaCallTrampoline(JNIJavaCallTrampolineHolder.java)

Printing instructions (ip=0x00000001005932d8):
  0x00000001005931d8: 0x00 0x1f 0xa0 0xf2 0x00 0x00 0xc0 0xf2 0x00 0x00 0xe0 0xf2 0x60 0x03 0x00 0x8b
  0x00000001005931e8: 0xe2 0x43 0x04 0x94 0x1f 0x20 0x03 0xd5 0xe0 0xb3 0x6d 0xb2 0xe2 0x03 0x01 0xaa
  0x00000001005931f8: 0x40 0x00 0x00 0x8a 0x03 0xc0 0x20 0x91 0x42 0x00 0x03 0xcb 0xe3 0x07 0x7c 0xb2
  0x0000000100593208: 0x62 0x24 0x42 0x8b 0x03 0x68 0xe2 0x38 0x23 0xfb 0xff 0x34 0x1f 0x68 0x22 0x38
  0x0000000100593218: 0xd7 0xff 0xff 0x17 0xe0 0xb3 0x6d 0xb2 0xe2 0x03 0x01 0xaa 0x40 0x00 0x00 0x8a
  0x0000000100593228: 0x03 0xc0 0x20 0x91 0x42 0x00 0x03 0xcb 0xe3 0x07 0x7c 0xb2 0x62 0x24 0x42 0x8b
  0x0000000100593238: 0x03 0x68 0xe2 0x38 0x43 0xfa 0xff 0x34 0x1f 0x68 0x22 0x38 0xd0 0xff 0xff 0x17
  0x0000000100593248: 0xe0 0xb3 0x6d 0xb2 0xe2 0x03 0x01 0xaa 0x40 0x00 0x00 0x8a 0x03 0xc0 0x20 0x91
  0x0000000100593258: 0x42 0x00 0x03 0xcb 0xe3 0x07 0x7c 0xb2 0x62 0x24 0x42 0x8b 0x03 0x68 0xe2 0x38
  0x0000000100593268: 0x83 0xf7 0xff 0x34 0x1f 0x68 0x22 0x38 0xba 0xff 0xff 0x17 0xbb 0x19 0xff 0x97
  0x0000000100593278: 0x1f 0x20 0x03 0xd5 0xe1 0x03 0x00 0xaa 0xaf 0xff 0xff 0x17 0xcc 0xcc 0xcc 0xcc
  0x0000000100593288: 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0xcc 0x08 0x5c 0x40 0xf9 0x08 0x01 0x02 0x8b
  0x0000000100593298: 0x08 0x1d 0x40 0xf9 0x00 0x01 0x1f 0xd6 0x08 0x5c 0x40 0xf9 0x08 0x01 0x03 0x8b
  0x00000001005932a8: 0x08 0x29 0x40 0xf9 0x00 0x01 0x1f 0xd6 0x08 0x5c 0x40 0xf9 0x08 0x01 0x02 0x8b
  0x00000001005932b8: 0x08 0x21 0x40 0xf9 0x00 0x01 0x1f 0xd6 0x08 0x5c 0x40 0xf9 0x08 0x01 0x03 0x8b
  0x00000001005932c8: 0x08 0x2d 0x40 0xf9 0x00 0x01 0x1f 0xd6 0x08 0x5c 0x40 0xf9 0x08 0x01 0x02 0x8b
> 0x00000001005932d8: 0x08 0x19 0x40 0xf9 0x00 0x01 0x1f 0xd6 0x08 0x5c 0x40 0xf9 0x08 0x01 0x03 0x8b
  0x00000001005932e8: 0x08 0x25 0x40 0xf9 0x00 0x01 0x1f 0xd6 0xff 0x83 0x05 0xd1 0xfd 0x7b 0x15 0xa9
  0x00000001005932f8: 0xe4 0x03 0x1b 0xaa 0xe5 0x03 0x1c 0xaa 0x40 0x02 0x00 0xb4 0xfc 0x03 0x00 0xaa
  0x0000000100593308: 0x06 0x5c 0x40 0xf9 0xfb 0x03 0x06 0xaa 0x88 0xe3 0x03 0x91 0x06 0xfd 0xdf 0x88
  0x0000000100593318: 0xc6 0x08 0x00 0x35 0xe6 0x07 0x00 0x32 0xe7 0x03 0x00 0x32 0x8a 0x53 0x00 0x91
  0x0000000100593328: 0xbf 0x3b 0x03 0xd5 0x4b 0xfd 0x5f 0x88 0x7f 0x01 0x06 0x6b 0x61 0x00 0x00 0x54
  0x0000000100593338: 0x47 0xfd 0x08 0x88 0x88 0xff 0xff 0x35 0xe6 0x17 0x9f 0x1a 0x66 0x07 0x00 0x34
  0x0000000100593348: 0x46 0x00 0x1b 0x8b 0xdf 0x00 0x1b 0xeb 0xe0 0x0a 0x00 0x54 0xee 0xbf 0x09 0xad
  0x0000000100593358: 0xec 0xb7 0x08 0xad 0xea 0xaf 0x07 0xad 0xe8 0xa7 0x06 0xad 0xe4 0x17 0x0c 0xa9
  0x0000000100593368: 0xf9 0x6b 0x0b 0xa9 0xf7 0x63 0x0a 0xa9 0xf5 0x5b 0x09 0xa9 0xf3 0x53 0x08 0xa9
  0x0000000100593378: 0xe6 0x13 0x00 0xf9 0xe1 0x8b 0x06 0xa9 0xe0 0x33 0x00 0xf9 0x60 0x00 0x40 0xfd
  0x0000000100593388: 0x61 0x88 0x40 0x6d 0x63 0x90 0x41 0x6d 0x65 0x14 0x40 0xfd 0x67 0x30 0x40 0xb9
  0x0000000100593398: 0xe3 0x3f 0x00 0xf9 0xe7 0x5f 0x00 0xb9 0xe4 0x97 0x04 0x6d 0xe2 0x8f 0x03 0x6d
  0x00000001005933a8: 0xe0 0x87 0x02 0x6d 0x41 0xfe 0xff 0x97 0x1f 0x20 0x03 0xd5 0xe6 0x13 0x40 0xf9
  0x00000001005933b8: 0xde 0x14 0x40 0xf9 0xe0 0x13 0x00 0xf9 0xe0 0x87 0x46 0xa9 0xe2 0x03 0x1f 0x2a
  0x00000001005933c8: 0xe0 0x87 0x42 0x6d 0xe2 0x8f 0x43 0x6d 0xe4 0x97 0x44 0x6d 0xe3 0x5f 0x40 0xb9

Top of stack (sp=0x0000000170196530):
  0x0000000170196510: 0x0000000000000000 0x0000000000000000 0x00000001701965a0 0x0000000129ac98e4
> 0x0000000170196530: 0x000000000000000a 0x000000000000000b 0x000000000000000a 0x0000000000000003
  0x0000000170196550: 0x0000000100000000 0x93124624617c006f 0x0000000000000002 0x0000000000000000
  0x0000000170196570: 0x0000000000000005 0x000000013ae04200 0x000000012dcbacc8 0x000000012dd195f8
  0x0000000170196590: 0x0000600003bb89c0 0x000000013ae04200 0x0000000170196610 0x0000000129acbbb4
  0x00000001701965b0: 0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000100000000
  0x00000001701965d0: 0x0000600001fb86c0 0x93124624617c006f 0x0000000000000005 0x000000013ae04200
  0x00000001701965f0: 0x0000000000000003 0x0000000000000001 0x00006000039a0170 0x0000600003bb8a80
  0x0000000170196610: 0x00000001701966d0 0x0000000129acf6e0 0x0000000000000000 0x0000600003bb8a80
  0x0000000170196630: 0x000000012dd195f8 0x0000600003bb8a20 0x0000000000000006 0x00006000039a0170
  0x0000000170196650: 0x00006000039a00c0 0x0000600003bb89e0 0x00006000039a0110 0x000000012dcbacc8
  0x0000000170196670: 0x000000013b026a00 0x0000000129b518c0 0x000000013ae04200 0x0000000300000000
  0x0000000170196690: 0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000129b4b268
  0x00000001701966b0: 0x0000000129b4b2f8 0x0000000129b80000 0x0000000129b4b268 0xfffffffe29b4b210
  0x00000001701966d0: 0x0000000170196fe0 0x0000000100081494 0x0000000000000004 0x0000000000000002
  0x00000001701966f0: 0x0000000000000005 0x0000000000000006 0x0000000000000000 0x0000000129acd9e8
  0x0000000170196710: 0x0000000170196fe0 0x000000010148d9cc 0x0000000129b00bc0 0x0000000129b51060

VM thread locals for the failing thread 0x000000013ae04200:
  0: JNIThreadLocalEnvironment.jniFunctions = (bytes) 0x00000003014a56b8
  8: StackOverflowCheckImpl.stackBoundaryTL = (Word) 0x0000000000000001 (1)
  16: Safepoint.safepointRequested = (int) 0x7f9c64cd (2140955853)
  20: StatusSupport.statusTL = (int) 0x00000001 (1)
  24: ThreadLocalAllocation.regularTLAB = (bytes)
    0x000000013ae04218: 0x0000000129b00000 0x0000000129b80000
    0x000000013ae04228: 0x0000000129b52150 0x000000012ac80000
  56: PlatformThreads.currentThread = (Object) 0x0000000129c00b40
    is an object of type io.vertx.core.impl.VertxThread
  64: JavaFrameAnchors.lastAnchor = (Word) 0x0000000170196750 (6175680336)
  72: JavaThreads.currentVThreadId = (long) 0x0000000000000030 (48)
  80: ExceptionUnwind.currentException = (Object) 0x0000000000000000
  88: IdentityHashCodeSupport.hashCodeGeneratorTL = (Object) 0x0000000129c03168
    is an object of type java.util.SplittableRandom
  96: IsolatedCompileClient.currentClient = (Object) 0x0000000000000000
  104: IsolatedCompileContext.currentContext = (Object) 0x0000000000000000
  112: JNIObjectHandles.handles = (Object) 0x0000000129c03198
    is an object of type com.oracle.svm.core.handles.ThreadLocalHandles
  120: JNIThreadLocalPendingException.pendingException = (Object) 0x0000000129b51e20
    is an object of type java.lang.NoSuchMethodError: ai.onnxruntime.TensorInfo.<init>([J[Ljava/lang/String;I)V
        at com.oracle.svm.core.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1347)
        at com.oracle.svm.core.jni.functions.JNIFunctions$Support.getMethodID(JNIFunctions.java:1332)
        ... 28 more
  128: JNIThreadLocalReferencedObjects.referencedObjectsListHead = (Object) 0x0000000129b518f0
    is an object of type com.oracle.svm.core.jni.JNIThreadLocalPrimitiveArrayViews$ReferencedObjectListNode
  136: JNIThreadOwnedMonitors.ownedMonitors = (Object) 0x0000000000000000
  144: NoAllocationVerifier.openVerifiers = (Object) 0x0000000000000000
  152: RecurringCallbackTimer.exception = (Object) 0x0000000000000000
  160: ThreadingSupportImpl.activeTimer = (Object) 0x0000000000000000
  168: SubstrateDiagnostics.threadOnlyAttachedForCrashHandler = (bytes) 0x0000000000000000
  176: ThreadLocalAllocation.allocatedBytes = (Word) 0x0000000015dff558 (366998872)
  184: VMThreads.IsolateTL = (Word) 0x0000000300000000 (12884901888)
  192: VMThreads.OSThreadHandleTL = (Word) 0x0000000170197000 (6175682560)
  200: VMThreads.OSThreadIdTL = (Word) 0x0000000000002b03 (11011)
  208: VMThreads.StackBase = (Word) 0x0000000170197000 (6175682560)
  216: VMThreads.StackEnd = (Word) 0x0000000170114000 (6175145984)
  224: VMThreads.StartedByCurrentIsolate = (bytes) 0x0000000000000001
  232: VMThreads.nextTL = (Word) 0x000000013ae04080 (5282742400)
  240: VMThreads.unalignedIsolateThreadMemoryTL = (Word) 0x000000013ae041d0 (5282742736)
  248: ActionOnTransitionToJavaSupport.actionTL = (int) 0x00000000 (0)
  252: ImplicitExceptions.implicitExceptionsAreFatal = (int) 0x00000000 (0)
  256: StackOverflowCheckImpl.yellowZoneStateTL = (int) 0x7efefefe (2130640638)
  260: StatusSupport.safepointBehaviorTL = (int) 0x00000001 (1)
  264: ThreadingSupportImpl.currentPauseDepth = (int) 0x00000000 (0)

Java frame anchors for the failing thread 0x000000013ae04200:
  Anchor 0x0000000170196750 LastJavaSP 0x00000001701966e0 LastJavaIP 0x0000000100081478

Stacktrace for the failing thread 0x000000013ae04200 (A=AOT compiled, J=JIT compiled, D=deoptimized, i=inlined):
  A  SP 0x0000000170196530 IP 0x00000001005932d8 size=16    com.oracle.svm.core.jni.JNIJavaCallTrampolineHolder.varargsJavaCallTrampoline(JNIJavaCallTrampolineHolder.java)
  SP 0x0000000170196540 IP 0x000000000000000b  IP is not within Java code. Aborting stack trace printing.

  Starting the stack walk in a possible caller (sp + 432):
  A  SP 0x00000001701966e0 IP 0x0000000100081494 size=240   ai.onnxruntime.OrtSession.run(Native Method)
  A  SP 0x00000001701967d0 IP 0x000000010007fa68 size=224   ai.onnxruntime.OrtSession.run(OrtSession.java:395)
  i  SP 0x00000001701968b0 IP 0x0000000100b8e080 size=128   ai.onnxruntime.OrtSession.run(OrtSession.java:242)
  i  SP 0x00000001701968b0 IP 0x0000000100b8e080 size=128   ai.onnxruntime.OrtSession.run(OrtSession.java:210)
  A  SP 0x00000001701968b0 IP 0x0000000100b8e080 size=128   dev.langchain4j.model.embedding.onnx.OnnxBertBiEncoder.encode(OnnxBertBiEncoder.java:139)
  A  SP 0x0000000170196930 IP 0x0000000100b8d498 size=112   dev.langchain4j.model.embedding.onnx.OnnxBertBiEncoder.embed(OnnxBertBiEncoder.java:75)
  A  SP 0x00000001701969a0 IP 0x0000000100b8c550 size=80    dev.langchain4j.model.embedding.onnx.AbstractInProcessEmbeddingModel.embedInTheSameThread(AbstractInProcessEmbeddingModel.java:80)
  A  SP 0x00000001701969f0 IP 0x0000000100b8c4a4 size=64    dev.langchain4j.model.embedding.onnx.AbstractInProcessEmbeddingModel.embedAll(AbstractInProcessEmbeddingModel.java:73)
  A  SP 0x0000000170196a30 IP 0x0000000100b8b97c size=96    dev.langchain4j.model.embedding.EmbeddingModel.embed(EmbeddingModel.java:34)
  A  SP 0x0000000170196a90 IP 0x0000000100b8bed0 size=48    dev.langchain4j.model.embedding.EmbeddingModel.embed(EmbeddingModel.java:24)
  A  SP 0x0000000170196ac0 IP 0x0000000100b91b80 size=48    dev.langchain4j.model.embedding.onnx.allminilml6v2.AllMiniLmL6V2EmbeddingModel_LMT_XZzHQocpw8D1rIWDkUyJxuw_Synthetic_ClientProxy.embed(Unknown Source)
  A  SP 0x0000000170196af0 IP 0x0000000101bb42e4 size=80    org.acme.test.InProcessEmbeddingResource.computeEmbedding(InProcessEmbeddingResource.java:21)
  A  SP 0x0000000170196b40 IP 0x0000000101bb420c size=48    org.acme.test.InProcessEmbeddingResource$quarkusrestinvoker$computeEmbedding_1e745afd3e71075c0629747f1d3b8bbb8ca4aa91.invoke(Unknown Source)
  A  SP 0x0000000170196b70 IP 0x0000000101e97a30 size=64    org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
  A  SP 0x0000000170196bb0 IP 0x0000000100faf784 size=48    io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
  A  SP 0x0000000170196be0 IP 0x0000000101e55930 size=112   org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
  A  SP 0x0000000170196c50 IP 0x000000010109c9e8 size=128   io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
  A  SP 0x0000000170196cd0 IP 0x0000000101eac1d0 size=48    org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
  A  SP 0x0000000170196d00 IP 0x0000000101eac2f8 size=80    org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
  A  SP 0x0000000170196d50 IP 0x0000000101ead37c size=112   org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
  i  SP 0x0000000170196dc0 IP 0x0000000101eb3294 size=48    org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
  A  SP 0x0000000170196dc0 IP 0x0000000101eb3294 size=48    org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
  A  SP 0x0000000170196df0 IP 0x0000000100e094c4 size=48    io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  i  SP 0x0000000170196e20 IP 0x00000001014b2e80 size=48    java.lang.Thread.runWith(Thread.java:1583)
  A  SP 0x0000000170196e20 IP 0x00000001014b2e80 size=48    java.lang.Thread.run(Thread.java:1570)
  A  SP 0x0000000170196e50 IP 0x00000001006ac570 size=64    com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:853)
  A  SP 0x0000000170196e90 IP 0x00000001006ac3bc size=48    com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:829)
  A  SP 0x0000000170196ec0 IP 0x000000010054354c size=272   com.oracle.svm.core.code.IsolateEnterStub.PlatformThreads_threadStartRoutine_7ca06a92d37709d55cf0945cbea8bdcde7f70f0e(IsolateEnterStub.java:0)

Threads:
  0x000000014c0041c0 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "vert.x-acceptor-thread-0" - 0x0000000129c00e58, stack(0x00000001707a4000,0x0000000170827000)
  0x000000014c204c00 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "vert.x-eventloop-thread-9" - 0x0000000129c010e8, stack(0x0000000170718000,0x000000017079b000)
  0x000000014c204a80 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "vert.x-eventloop-thread-8" - 0x0000000129c01378, stack(0x000000017068c000,0x000000017070f000)
  0x000000013ba04080 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "vert.x-eventloop-thread-7" - 0x0000000129c01608, stack(0x0000000170600000,0x0000000170683000)
  0x000000013b804200 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "vert.x-eventloop-thread-6" - 0x0000000129c01898, stack(0x0000000170574000,0x00000001705f7000)
  0x000000013ae045c0 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "vert.x-eventloop-thread-5" - 0x0000000129c01b28, stack(0x00000001704e8000,0x000000017056b000)
  0x000000013b904200 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "vert.x-eventloop-thread-4" - 0x0000000129c01db8, stack(0x000000017045c000,0x00000001704df000)
  0x000000013b904080 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "vert.x-eventloop-thread-3" - 0x0000000129c02048, stack(0x00000001703d0000,0x0000000170453000)
  0x000000013b804080 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "vert.x-eventloop-thread-2" - 0x0000000129c022d8, stack(0x0000000170344000,0x00000001703c7000)
  0x000000013ae04480 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "vert.x-eventloop-thread-1" - 0x0000000129c02568, stack(0x00000001702b8000,0x000000017033b000)
  0x000000013af04080 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "vert.x-eventloop-thread-0" - 0x0000000129c027f8, stack(0x000000017022c000,0x00000001702af000)
  0x000000013ae04340 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "vertx-blocked-thread-checker" - 0x0000000129c02910, daemon, stack(0x00000001701a0000,0x0000000170223000)
  0x000000013ae04200 STATUS_IN_JAVA (PREVENT_VM_FROM_REACHING_SAFEPOINT) "executor-thread-1" - 0x0000000129c00b40, daemon, stack(0x0000000170114000,0x0000000170197000)
  0x000000013ae04080 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "Reference Reaper #1" - 0x0000000129c02ae0, daemon, stack(0x0000000170088000,0x000000017010b000)
  0x000000014ae05b80 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "Signal Dispatcher" - 0x0000000129c02bd8, daemon, stack(0x000000016fe58000,0x000000016fedb000)
  0x000000014ae056c0 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "Reference Handler" - 0x00000003024b4818, daemon, stack(0x000000016fdcc000,0x000000016fe4f000)
  0x000000014af04080 STATUS_IN_NATIVE (ALLOW_SAFEPOINT) "main" - 0x00000003024b4458, stack(0x000000016f5cc000,0x000000016fdc8000)

No VMOperation in progress

The 30 most recent VM operation status changes:
  1.363s - Started Garbage collection (safepoint: true, queueingThread: 0x000000013ae04200, executingThread: 0x000000013ae04200, safepointId: 1)
  1.369s - Finished Garbage collection (safepoint: true, queueingThread: 0x000000013ae04200, executingThread: 0x000000013ae04200, safepointId: 1)
  1.376s - Started Garbage collection (safepoint: true, queueingThread: 0x000000014ae056c0, executingThread: 0x000000014ae056c0, safepointId: 2)
  1.378s - Finished Garbage collection (safepoint: true, queueingThread: 0x000000014ae056c0, executingThread: 0x000000014ae056c0, safepointId: 2)
  1.449s - Started Garbage collection (safepoint: true, queueingThread: 0x000000013ae04200, executingThread: 0x000000013ae04200, safepointId: 3)
  1.453s - Finished Garbage collection (safepoint: true, queueingThread: 0x000000013ae04200, executingThread: 0x000000013ae04200, safepointId: 3)
  1.472s - Started Garbage collection (safepoint: true, queueingThread: 0x000000013ae04200, executingThread: 0x000000013ae04200, safepointId: 4)
  1.472s - Finished Garbage collection (safepoint: true, queueingThread: 0x000000013ae04200, executingThread: 0x000000013ae04200, safepointId: 4)

VM mutexes:
  mutex "RealLog.backTracePrinterMutex" is unlocked.
  mutex "mainVMOperationControlWorkQueue" is unlocked.
  mutex "outOfMemoryHeapDump" is unlocked.
  mutex "referencePendingList" is unlocked.
  mutex "thread" is unlocked.

Build time information:
  Version: 22.0.2+9, serial gc
  Platform: darwin/aarch64
  Page size: 16384
  Container support: true
  CPU features used for AOT compiled code: FP, ASIMD

Runtime information:
  CPU cores (container): 10
  CPU cores (OS): 10
  Memory: 32768M
  Page size: 16384
  VM uptime: 1.578s
  Current timestamp: 1727807527767
  AOT compiled code: 0x000000010003c000 - 0x00000001026d8e8f

Command line:

Heap settings and statistics:
  Supports isolates: true
  Heap base: 0x0000000300000000
  Object reference size: 8
  Reserved object header bits: 0b111
  Aligned chunk size: 524288
  Large array threshold: 131072
  Incremental collections: 4
  Complete collections: 3

Heap usage:
  Eden: 7.58M (0.00M in 0 aligned chunks, 0.00M in 0 unaligned chunks)
  Old: 216.76M (2.00M in 4 aligned chunks, 214.76M in 2 unaligned chunks)

Native image heap boundaries:
  ReadOnly Primitives: 0x0000000300080830 - 0x0000000300d537a0
  ReadOnly References: 0x0000000300d537a0 - 0x00000003014a20c8
  ReadOnly Relocatables: 0x00000003014a4000 - 0x0000000301aefbd0
  Writable Primitives: 0x0000000301af0000 - 0x0000000302151798
  Writable References: 0x0000000302151798 - 0x00000003038f77f0
  Writable Huge: 0x0000000303900038 - 0x0000000303a70a00
  ReadOnly Huge: 0x0000000303a74038 - 0x0000000324d53ec0

Heap chunks: E=eden, S=survivor, O=old, F=free; A=aligned chunk, U=unaligned chunk; T=to space
  |0x0000000129c00000|0x0000000129c00830, 0x0000000129c7fff0, 0x0000000129c80000| 99%|  O|A|
  |0x0000000129b80000|0x0000000129b80830, 0x0000000129c00000, 0x0000000129c00000|100%|  O|A|
  |0x0000000127980000|0x0000000127980830, 0x00000001279fffe0, 0x0000000127a00000| 99%|  O|A|
  |0x0000000129c80000|0x0000000129c80830, 0x0000000129c8fc30, 0x0000000129d00000| 11%|  O|A|
  |0x0000000158000000|0x0000000158000038, 0x0000000160000048, 0x0000000160000048|100%|  O|U|
  |0x0000000160004000|0x0000000160004038, 0x00000001656c8f28, 0x00000001656c8f28|100%|  O|U|
  |0x000000012ae80000|0x000000012ae80830, 0x000000012ae80830, 0x000000012af00000|  0%|  F|A|
  |0x000000012af00000|0x000000012af00830, 0x000000012af00830, 0x000000012af80000|  0%|  F|A|
  |0x000000012c880000|0x000000012c880830, 0x000000012c880830, 0x000000012c900000|  0%|  F|A|
  |0x000000012c900000|0x000000012c900830, 0x000000012c900830, 0x000000012c980000|  0%|  F|A|
  |0x0000000129e80000|0x0000000129e80830, 0x0000000129e80830, 0x0000000129f00000|  0%|  F|A|
  |0x0000000129f80000|0x0000000129f80830, 0x0000000129f80830, 0x000000012a000000|  0%|  F|A|
  |0x0000000127a00000|0x0000000127a00830, 0x0000000127a00830, 0x0000000127a80000|  0%|  F|A|
  |0x0000000127a80000|0x0000000127a80830, 0x0000000127a80830, 0x0000000127b00000|  0%|  F|A|
  |0x0000000129d80000|0x0000000129d80830, 0x0000000129d80830, 0x0000000129e00000|  0%|  F|A|
  |0x0000000129e00000|0x0000000129e00830, 0x0000000129e00830, 0x0000000129e80000|  0%|  F|A|
  |0x0000000129f00000|0x0000000129f00830, 0x0000000129f00830, 0x0000000129f80000|  0%|  F|A|
  |0x000000012a000000|0x000000012a000830, 0x000000012a000830, 0x000000012a080000|  0%|  F|A|
  |0x000000012a100000|0x000000012a100830, 0x000000012a100830, 0x000000012a180000|  0%|  F|A|
  |0x000000012a600000|0x000000012a600830, 0x000000012a600830, 0x000000012a680000|  0%|  F|A|
  |0x000000012a180000|0x000000012a180830, 0x000000012a180830, 0x000000012a200000|  0%|  F|A|
  |0x000000012a200000|0x000000012a200830, 0x000000012a200830, 0x000000012a280000|  0%|  F|A|
  |0x000000012a280000|0x000000012a280830, 0x000000012a280830, 0x000000012a300000|  0%|  F|A|
  |0x000000012a300000|0x000000012a300830, 0x000000012a300830, 0x000000012a380000|  0%|  F|A|
  |0x000000012a380000|0x000000012a380830, 0x000000012a380830, 0x000000012a400000|  0%|  F|A|
  |0x000000012a400000|0x000000012a400830, 0x000000012a400830, 0x000000012a480000|  0%|  F|A|
  |0x000000012a480000|0x000000012a480830, 0x000000012a480830, 0x000000012a500000|  0%|  F|A|
  |0x000000012a500000|0x000000012a500830, 0x000000012a500830, 0x000000012a580000|  0%|  F|A|
  |0x000000012a580000|0x000000012a580830, 0x000000012a580830, 0x000000012a600000|  0%|  F|A|
  |0x0000000129d00000|0x0000000129d00830, 0x0000000129d00830, 0x0000000129d80000|  0%|  F|A|

Segfault detected, aborting process. Use '-XX:-InstallSegfaultHandler' to disable the segfault handler at run time and create a core dump instead. Rebuild with '-R:-InstallSegfaultHandler' to disable the handler permanently at build time.
```

(at runtime, not build time obviously)

**Comment by geoand** [comment]
They should be...

**Comment by cescoffier** [comment]
Pretty sure they are not, tokenizer locations are out of date.

**Comment by cescoffier** [comment]
(I will fix that at the same time)

**Comment by cescoffier** [comment]
Ok, they all segfault, even with the right tokenizer location.

**Comment by geoand** [comment]
I see...

**Comment by cescoffier** [comment]
Ok, let's take a step back and separate the different issues:

1. The in process embedding processor is out of data and the tokenizer are not correct (I will open a PR about that)
2. In process embedding integration-tests are not passing in native (and not executed in the CI) - that would be a second PR, but we will need to investigate the segfault 
3. Having multiple tests in core/deployment touching local embedding loads embedding twice in 2 different classloaders. There may be a trick to fix that, but we could also move these tests to integration-tests and avoid the issue altogether.
4. Add support for BGE 1.5 - for easyrag, I think it makes sense to exclude it, to avoid bringing an embedding model in the classpath which would break `@Inject EmbeddingModel model`.

**Comment by cescoffier** [comment]
hum, the workflow says:

```
          # skip RAG module as it doesn't have any native-compatible tests now
          # skip 'embed' modules (with in-process embeddings) and others that don't work in native
```

**Comment by cescoffier** [comment]
Ok, the seg fault is due to an:
`Stop reason: EXC_BAD_ACCESS (code=2, address=0x128900030)`

in the convertToTensorInfo method (C++)
