### ISSUE TITLE
Cohere API doesn't seem to work

### ISSUE THREAD

**Issue by edeandrea** [quarkiverse/quarkus-langchain4j#957]
When I try to add the cohere extension it blows up:

```java
public class RagRetriever {

    @Produces
    @ApplicationScoped
    public RetrievalAugmentor create(
                  EmbeddingStore store,
                  EmbeddingModel model,
                  ChatLanguageModel chatLanguageModel,
                  WebSearchEngine webSearchEngine,
                  ScoringModel scoringModel) {

        var embeddingStoreContentRetriever = EmbeddingStoreContentRetriever.builder()
                .embeddingModel(model)
                .embeddingStore(store)
                .maxResults(3)
                .build();

        var webSearchContentRetriever = WebSearchContentRetriever.builder()
          .webSearchEngine(webSearchEngine)
          .build();

        var queryRouter = LanguageModelQueryRouter.builder()
          .chatLanguageModel(chatLanguageModel)
          .fallbackStrategy(FallbackStrategy.ROUTE_TO_ALL)
          .retrieverToDescription(
            Map.of(
              embeddingStoreContentRetriever, "Local documents",
              webSearchContentRetriever, "Search of quarkus.io"
            )
          )
          .build();

        var contentAggregator = ReRankingContentAggregator.builder()
          .scoringModel(scoringModel)
          .querySelector(ReRankingContentAggregator.DEFAULT_QUERY_SELECTOR)
          .minScore(0.6)
          .build();

        return DefaultRetrievalAugmentor.builder()
                .queryRouter(queryRouter)
                .queryTransformer(new CompressingQueryTransformer(chatLanguageModel))
                .contentAggregator(contentAggregator)
                .contentInjector((list, userMessage) -> {
                    StringBuffer prompt = new StringBuffer(userMessage.singleText());
                    prompt.append("\nPlease, only use the following information:\n");

                    list.stream()
                      .map(content -> "- %s\n".formatted(content.textSegment().text()))
                      .forEach(prompt::append);

                    return new UserMessage(prompt.toString());
                })
                .build();
    }
}
```

```
quarkus.langchain4j.cohere.api-key=${COHERE_API_KEY}
quarkus.langchain4j.cohere.scoring-model.model-name=command-r-08-2024
```

```
2024-10-01 14:31:03,997 ERROR [dev.lan.qua.wor.DocumentationChatAgentWebSocket] (vert.x-worker-thread-1) error occurred during chat: org.jboss.resteasy.reactive.ClientWebApplicationException: Received: 'Bad Request, status code 400' when invoking REST Client method: 'io.quarkiverse.langchain4j.cohere.runtime.api.CohereApi#rerank': java.lang.RuntimeException: org.jboss.resteasy.reactive.ClientWebApplicationException: Received: 'Bad Request, status code 400' when invoking REST Client method: 'io.quarkiverse.langchain4j.cohere.runtime.api.CohereApi#rerank'
        at dev.langchain4j.internal.RetryUtils$RetryPolicy.withRetry(RetryUtils.java:195)
        at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:229)
        at io.quarkiverse.langchain4j.cohere.runtime.QuarkusCohereScoringModel.scoreAll(QuarkusCohereScoringModel.java:73)
        at io.quarkiverse.langchain4j.cohere.runtime.QuarkusCohereScoringModel_5bBhGb7TX5yqAqboT1wD3egbn18_Synthetic_ClientProxy.scoreAll(Unknown Source)
        at dev.langchain4j.rag.content.aggregator.ReRankingContentAggregator.reRankAndFilter(ReRankingContentAggregator.java:115)
        at dev.langchain4j.rag.content.aggregator.ReRankingContentAggregator.aggregate(ReRankingContentAggregator.java:97)
        at dev.langchain4j.rag.DefaultRetrievalAugmentor.augment(DefaultRetrievalAugmentor.java:156)
        at dev.langchain4j.rag.RagRetriever_ProducerMethod_create_LHxC5suGFqAaAvPdbe828pjDFlU_ClientProxy.augment(Unknown Source)
        at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport$2.get(AiServiceMethodImplementationSupport.java:178)
        at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport$2.get(AiServiceMethodImplementationSupport.java:175)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.jboss.resteasy.reactive.ClientWebApplicationException: Received: 'Bad Request, status code 400' when invoking REST Client method: 'io.quarkiverse.langchain4j.cohere.runtime.api.CohereApi#rerank'
        at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext.unwrapException(RestClientRequestContext.java:205)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.handleException(AbstractResteasyReactiveContext.java:329)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:175)
        at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext$1.lambda$execute$0(RestClientRequestContext.java:324)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:252)
        at io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:50)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        ... 2 more
Caused by: jakarta.ws.rs.WebApplicationException: Bad Request, status code 400
        at io.quarkus.rest.client.reactive.runtime.DefaultMicroprofileRestClientExceptionMapper.toThrowable(DefaultMicroprofileRestClientExceptionMapper.java:19)
        at io.quarkus.rest.client.reactive.runtime.MicroProfileRestClientResponseFilter.filter(MicroProfileRestClientResponseFilter.java:54)
        at org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler.handle(ClientResponseFilterRestHandler.java:21)
        at org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler.handle(ClientResponseFilterRestHandler.java:10)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.invokeHandler(AbstractResteasyReactiveContext.java:231)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        ... 12 more
```

**Comment by jmartisk** [comment]
I'll have a look, but things have really piled up big time now, so it may take me a while.

**Comment by geoand** [comment]
I have a few minutes to spare. If it's an easy fix, I'll do it, otherwise it will go into the normal queue

**Comment by geoand** [comment]
I could not reproduce the problem, so I'll need a sample

**Comment by jmartisk** [comment]
Not sure where you got the `command-r-08-2024` model, https://docs.cohere.com/reference/rerank mentions `rerank-english-v3.0, rerank-multilingual-v3.0, rerank-english-v2.0, rerank-multilingual-v2.0` as supported

**Comment by jmartisk** [comment]
Hm you seem to be using a Command model (https://docs.cohere.com/docs/models#command) but you need a Rerank model (https://docs.cohere.com/docs/models#rerank) we may need to improve the JavaDoc to make is clearer (the docs seem to have changed since I wrote it)

**Comment by edeandrea** [comment]
Could be user error :) I'll try it again

**Comment by edeandrea** [comment]
Yep this was user error. I wasn't using the correct model....Sorry about that!

One thing I noticed though is that I don't get the request/response logs printed to/from cohere, and there doesn't seem to be a config option for it. I'll create a new issue for that enhancement.
