### ISSUE TITLE
quarkus-langchain4j v0.20.3 fails to start

### ISSUE THREAD

**Issue by andreadimaio** [quarkiverse/quarkus-langchain4j#967]
When I try to start the application I have this error:
```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.langchain4j.deployment.devui.OpenWebUIDevUIProcessor#registerOpenWebUiCard threw an exception: java.lang.NoSuchMethodError: 'void io.quarkus.deployment.annotations.BuildProducer.produce(java.util.Collection)'
        at io.quarkiverse.langchain4j.deployment.devui.OpenWebUIDevUIProcessor.registerOpenWebUiCard(OpenWebUIDevUIProcessor.java:169)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.jboss.threads.JBossThread.run(JBossThread.java:483)
```

Maybe the line `OpenWebUIDevUIProcessor.java:169` should be  
```java
buildTimeActions.forEach(buildTimeActionProducer::produce);
```

**Comment by geoand** [comment]
cc @phillip-kruger @jmartisk

**Comment by jmartisk** [comment]
What Quarkus are you using? We now started requiring 3.15+

**Comment by andreadimaio** [comment]
> What Quarkus are you using? We now started requiring 3.15+. A NoSuchMethodError sounds like you're using an older version

Moved project to latest version of quarkus and everything works now. Thank you.

**Comment by geoand** [comment]
👍🏽

**Comment by jmartisk** [comment]
Yeah maybe we could add a build step that checks the Quarkus version and throws an error early in this case

**Comment by jmartisk** [comment]
I've reported https://github.com/quarkiverse/quarkus-langchain4j/issues/971 for that
