### ISSUE TITLE
Anthropic chat model not available when enabled.

### ISSUE THREAD

**Issue by dennysfredericci** [quarkiverse/quarkus-langchain4j#984]
Hey all,

I just have found a small issue, the anthropic chat model is not available when the property `quarkus.langchain4j.anthropic.chat-model.enabled` is set to true.

When it is set to true we will see the exception below:

````
Caused by: io.quarkus.runtime.configuration.ConfigurationException: A ChatLanguageModel or StreamingChatLanguageModel bean was requested, but no langchain4j providers were configured. Consider adding an extension like 'quarkus-langchain4j-openai'
        at io.quarkiverse.langchain4j.deployment.BeansProcessor.selectProvider(BeansProcessor.java:267)
        at io.quarkiverse.langchain4j.deployment.BeansProcessor.handleProviders(BeansProcessor.java:140)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:856)
````

The root cause seems to be a missing piece of code at [AnthropicProcessor](https://github.com/quarkiverse/quarkus-langchain4j/blob/b3bd6cfaf6e53038e96356fd6123240fb9b433e0/model-providers/anthropic/deployment/src/main/java/io/quarkiverse/langchain4j/anthropic/deployment/AnthropicProcessor.java#L37)

I have created a project to reproduce the issue [here](https://github.com/dennysfredericci/quarkus-langchain4j-anthropic)

**Comment by geoand** [comment]
Thanks for reporting!

You would to contribute a fix for the issue?

**Comment by dennysfredericci** [comment]
Yeah... I realize I have spent more time writing this issue and the project to reproduce than fixing... 😅...

I will do it later this week...

**Comment by geoand** [comment]
🙏🏽

**Comment by dennysfredericci** [comment]
PR: https://github.com/quarkiverse/quarkus-langchain4j/pull/985
